--RUN
SELECT * FROM JBPM4_EXECUTION WHERE JBPM4_EXECUTION.HISACTINST_ IN(SELECT DBID_ FROM JBPM4_HIST_ACTINST WHERE JBPM4_HIST_ACTINST.HPROCI_ IN(SELECT DBID_ FROM JBPM4_HIST_PROCINST));
SELECT * FROM JBPM4_TASK WHERE JBPM4_TASK.PROCINST_ IN(SELECT DBID_ FROM JBPM4_HIST_PROCINST) ;
--HISTORY
SELECT
   JBPM4_HIST_ACTINST_DBID_,
   JBPM4_HIST_ACTINST_LAST_DBID_,
   PREV_JBPM4_HIST_ACTINST_DBID_
 FROM T_JBPM_WORKFLOW_INFO;
SELECT * FROM JBPM4_HIST_TASK WHERE DBID_ IN(SELECT JBPM4_HIST_ACTINST.HTASK_ FROM JBPM4_HIST_ACTINST WHERE JBPM4_HIST_ACTINST.HPROCI_ IN(SELECT DBID_ FROM JBPM4_HIST_PROCINST));
SELECT * FROM JBPM4_HIST_ACTINST WHERE JBPM4_HIST_ACTINST.HPROCI_ IN(SELECT DBID_ FROM JBPM4_HIST_PROCINST);
SELECT JBPM4_HIST_PROCINST_DBID_ FROM T_JBPM_WORKFLOW_INFO;
SELECT * FROM JBPM4_HIST_PROCINST;