/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-03-02 09:58:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.solutions.leasing.cust_005finfo.cust_005faccount;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cust_005faccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tlds/minidict.tld", Long.valueOf(1486341662546L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmini_005fuser_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fmini_005fuser_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody != null) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.release();
    if (_005fjspx_005ftagPool_005fmini_005fuser_005fnobody != null) _005fjspx_005ftagPool_005fmini_005fuser_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(function() {\r\n");
      out.write("\tvar custaccountData;\r\n");
      out.write("\tvar showTools = true;\r\n");
      out.write("\tif('");
      if (_jspx_meth_mini_005fparam_005f0(_jspx_page_context))
        return;
      out.write("' == 'true'){showTools = false;}\r\n");
      out.write("\tseajs.use([ \"js/apcomponent/aptable/aptable.js\" ], function(ApTable) { \r\n");
      out.write("  \t\t\t\tnew ApTable({\r\n");
      out.write("  \t\t\t\t    id:'table_id2',  \t\t\t\t  \t\r\n");
      out.write("  \t\t\t\t  \trenderTo:'content_table_id2',  \t\t\t\t    \r\n");
      out.write("\t\t\t\t\twidth:globalClientWidth,\r\n");
      out.write("  \t\t\t\t\theight:globalClientHeight,   \r\n");
      out.write("  \t\t\t\t\teditFormPopupWindowWidth:700,\r\n");
      out.write("  \t\t\t\t\teditFormPopupWindowHeight:350,\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ticonCls:'icon-node',\r\n");
      out.write("\t\t\t\t\thiddenQueryArea:true,\r\n");
      out.write("\t\t\t\t\tshowToolbar: showTools,\r\n");
      out.write("\t\t\t\t\tvalidateForm:function(miniTable, miniForm, editFormItemOperFlag){\r\n");
      out.write("\t\t\t\t\t\tif(checkIsMain()==\"repeat\") return;\r\n");
      out.write("\t\t\t\t\t\tif(checkCustBankRepeat()==\"repeat\") return;\r\n");
      out.write("\t\t\t\t\t\tvar accnumber = mini.getbyName(\"accnumber\");\r\n");
      out.write("\t\t\t\t\t\tvar accnumbervalue = accnumber.getValue().replace(/[ ]/g,\"\");\r\n");
      out.write("\t\t\t\t\t\tif (isNaN(accnumbervalue)) { \r\n");
      out.write("\t\t\t\t\t\t\tmini.alert(\"银行账号请输入数字！\");\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\taccnumber.setValue(accnumbervalue);\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tafterShowWindowCallBack: function(miniTable,miniForm,operFlag){\r\n");
      out.write("\t\t\t\t\t\tif(\"add\" == operFlag){\r\n");
      out.write("\t\t\t\t\t\t\tif(custaccountData){\r\n");
      out.write("\t\t\t\t\t\t\t\tminiForm.setData(custaccountData);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t        url: urlPrefix+\"/eleasing/jsp/cust_info/cust_account/get_custinfo_byid.xml\",\r\n");
      out.write("\t\t\t\t\t\t\t        type: \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t        cache: false, \r\n");
      out.write("\t\t\t\t\t\t\t        async:false,\r\n");
      out.write("\t\t\t\t\t\t\t        data :{\"custid\":custid},\r\n");
      out.write("\t\t\t\t\t\t\t        success: function (text) {\t\t\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t            var result = mini.decode(text);\r\n");
      out.write("\t\t\t\t\t\t\t            var data = result.datas[0];\r\n");
      out.write("\t\t\t\t\t\t\t            var formData = miniForm.getData();\r\n");
      out.write("\t\t\t\t\t\t\t            $.extend(formData,mini.decode(data));\r\n");
      out.write("\t\t\t\t\t\t\t            miniForm.setData(formData);\r\n");
      out.write("\t\t\t\t\t\t\t            custaccountData = formData;\r\n");
      out.write("\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(\"edit\" == operFlag){\r\n");
      out.write("\t\t\t\t\t\t\tchangeaccnumber();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tremoteOper:true,\r\n");
      out.write("\t\t\t\t\tentityClassName:'com.tenwa.leasing.entity.cust.CustInfoAccount',\r\n");
      out.write("\t\t\t\t\tpageSize:15,\r\n");
      out.write("\t\t\t\t\tshowPager:true,\r\n");
      out.write("\t\t\t\t\tlazyLoad:false,\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\txmlFileName:'/eleasing/jsp/cust_info/cust_account/cust_account_info.xml',\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tparams:{custid:custid},\r\n");
      out.write("\t\t\t\t\ttools:[ 'add', '-', 'edit', '-', 'remove'],\r\n");
      out.write("\t\t\t\t\tcolumns:[ \r\n");
      out.write("\t\t\t\t\t        {type:'indexcolumn'},\r\n");
      out.write("\t\t\t\t\t        {type:'checkcolumn'}, \r\n");
      out.write("\t\t\t\t\t \t    {field:'id',header:'记录编号',headerAlign:'center',width:100,allowSort:true,visible:false,\r\n");
      out.write("\t  \t\t\t\t\t\t          formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t              readOnly:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t          fieldVisible:false }},\r\n");
      out.write("\t\t\t\t\t\t    {field:'custid',header:'客户ID',headerAlign:'center',width:100,allowSort:true,visible:false,\r\n");
      out.write("\t  \t\t\t\t\t\t         formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t             readOnly:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t         fieldVisible:false }},\r\n");
      out.write("\t  \t\t\t\t\t    {field: 'custname',header:'客户名',headerAlign:'center',width:100,allowSort:true,\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t              colspan: 3,\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text', \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t         fieldVisible:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:\"100%\",\r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:120 ,\r\n");
      out.write("\t\t\t\t\t\t\t\t             readonly:true }},\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'account',header:'帐户名称',headerAlign:'center', width:100,allowSort:true,\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t        formEditorConfig:{\t\r\n");
      out.write("\t\t\t\t\t\t\t\t            required:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t             newLine:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                type:'text',  \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t          labelWidth:100,\r\n");
      out.write("\t  \t\t\t\t\t\t\t               width:200}},\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'ismain',header:'是否主账户',headerAlign:'center',width:100,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t        formEditorConfig:{\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                type:'combobox',\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t          labelWidth:100,\r\n");
      out.write("\t\t\t\t\t\t\t\t               width:200,\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t          valueField:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t           textField:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t                data:[{text:'是'},{text:'否'}]}},\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'bankname',header:'开户银行',\theaderAlign:'center', width:100,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tformEditorConfig:{\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t             newLine:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                type:'text',\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                required:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t          labelWidth:100,\r\n");
      out.write("\t\t\t\t\t\t\t\t               width:200}},\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'accnumber',header:'银行账号',headerAlign:'center', width:100,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t                renderer:function(e){\r\n");
      out.write("\t\t\t\t\t\t\t\t                 var accnumbervalue = e.record.accnumber;\r\n");
      out.write("\t\t\t\t\t\t\t\t                 var formatvalue = accnumbervalue.replace(/(\\d{4})(?=\\d)/g,\"$1 \");\r\n");
      out.write("\t\t\t\t\t\t\t\t                 return formatvalue;},\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t             required:true,\r\n");
      out.write("\t\t\t\t\t\t\t \t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:200,\r\n");
      out.write("\t\t\t\t\t\t\t\t              onkeyup:\"changeaccnumber\"}},\r\n");
      out.write("\t\t\t\t\t\t   {field: 'accinfo',header:'帐户使用情况',headerAlign:'center',width:100,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{ \t\r\n");
      out.write("\t\t\t\t\t\t\t\t              colspan:3,\r\n");
      out.write("\t\t\t\t\t\t\t\t              newLine:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'textarea',  \r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t                                    width:\"100%\"}},\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'creatorname',header:'登记人',headerAlign:'center' ,width:100,allowSort:true,\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t              newLine:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t             readOnly:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                value:'");
      if (_jspx_meth_mini_005fuser_005f0(_jspx_page_context))
        return;
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:200}},\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   {field: 'createdate',header:'登记时间',headerAlign:'center',dateFormat:\"yyyy-MM-dd \",width:100,allowSort:true, \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t             readOnly:true,\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t         defaultValue:mini.formatDate(new Date(), \"yyyy-MM-dd\"),\r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:200}},\r\n");
      out.write("\t\t\t\t\t\t   {field: 'modificatorname',header:'修改人',headerAlign:'center' ,width:100,visible:false,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t              newLine:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t             readOnly:true, \r\n");
      out.write("\t\t\t\t\t\t\t\t         fieldVisible:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:200}},\r\n");
      out.write("\t\t\t\t\t\t  {field: 'modifydate',header:'修改时间',headerAlign:'center', visible:false,dateFormat:\"yyyy-MM-dd \",width:100,allowSort:true,\r\n");
      out.write("\t\t\t\t\t\t\t         formEditorConfig:{\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                 type:'text',\r\n");
      out.write("\t\t\t\t\t\t\t\t             readOnly:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t         fieldVisible:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t           labelWidth:100,\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                width:200 \t\t\t\t\t\t\t\t\r\n");
      out.write("\t  \t\t\t\t\t\t} \t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("  \tfunction changeaccnumber(e){\r\n");
      out.write("  \t\tvar accnumber = mini.getbyName(\"accnumber\");\r\n");
      out.write("  \t\tvar formatvalue = accnumber.getInputText().replace(/[^0-9.]/gi,\"\");\r\n");
      out.write("  \t\tvar accnumbervalue = formatvalue.replace(/(\\d{4})(?=\\d)/g,\"$1 \");\r\n");
      out.write("  \t\taccnumber.setValue(accnumbervalue);\r\n");
      out.write("  \t}\t\t\r\n");
      out.write("  \tfunction checkIsMain(){\r\n");
      out.write("  \t\tvar isMainvalue = getMiniEditFormField(\"table_id2.ismain\").getValue();//mini.getbyName(\"ismain\").getValue();\r\n");
      out.write("  \t\tif(\"\" == isMainvalue || \"否\" == isMainvalue)return \"\";\r\n");
      out.write("  \t\tvar idvalue = getMiniEditFormField(\"table_id2.id\").getValue();//mini.getbyName(\"id\").getValue();\r\n");
      out.write("  \t\tvar str = \"\";\r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("  \t        url: getRootPath()+\"/acl/checkIsMain.acl?Random=\" + Math.random(),\r\n");
      out.write("  \t        type: \"post\",\r\n");
      out.write("  \t        cache: false, \r\n");
      out.write("  \t        data :{\"id\":idvalue,\"custId\":custid},\r\n");
      out.write("  \t        async:false,\r\n");
      out.write("  \t        success: function (text) {\r\n");
      out.write("  \t        \tvar obj=mini.decode(text);\r\n");
      out.write("  \t        \tif(\"repeat\" == obj.message){\r\n");
      out.write("  \t        \t\tmini.alert(\"主账户只能有一个！\");\r\n");
      out.write("  \t        \t}\r\n");
      out.write("  \t        \tstr = obj.message;\r\n");
      out.write("  \t        }\r\n");
      out.write("  \t    });\r\n");
      out.write("  \t\treturn str;\r\n");
      out.write("  \t}\r\n");
      out.write("  \tfunction checkCustBankRepeat(){\r\n");
      out.write("  \t\tvar accNumber = getMiniEditFormField(\"table_id2.accnumber\").getValue();//mini.getbyName(\"mainpersonflag\").getValue();\r\n");
      out.write("  \t\tif(\"\" == accNumber)return \"\";\r\n");
      out.write("  \t\tvar idvalue = getMiniEditFormField(\"table_id2.id\").getValue();\r\n");
      out.write("  \t\taccNumber=accNumber.replace(/[ ]/g,\"\")\r\n");
      out.write("  \t\tvar str = \"\";\r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("  \t        url: getRootPath()+\"/acl/checkCustAccountRepeat.acl\",\r\n");
      out.write("  \t        type: \"post\",\r\n");
      out.write("  \t        cache: false, \r\n");
      out.write("  \t        data :{\"id\":idvalue,\"custId\":custid,\"accNumber\":accNumber},\r\n");
      out.write("  \t        async:false,\r\n");
      out.write("  \t        success: function (text) {\r\n");
      out.write("  \t        \tvar obj=mini.decode(text);\r\n");
      out.write("  \t        \tstr =\"repeat\";\r\n");
      out.write("  \t        \tif(obj.message.length>1){\r\n");
      out.write("  \t        \t\tmini.alert(obj.message);\r\n");
      out.write("  \t        \t}else{\r\n");
      out.write("  \t        \t\tstr =\"\";\r\n");
      out.write("  \t        \t}\r\n");
      out.write("  \t        \t\r\n");
      out.write("  \t        }\r\n");
      out.write("  \t    });\r\n");
      out.write("  \t\treturn str;\r\n");
      out.write("  \t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<div id='content_table_id2'></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mini_005fparam_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f0 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f0.setParent(null);
    // /WEB-INF/jsps/solutions/leasing/cust_info/cust_account/cust_account.jsp(7,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f0.setName("isView");
    int _jspx_eval_mini_005fparam_005f0 = _jspx_th_mini_005fparam_005f0.doStartTag();
    if (_jspx_th_mini_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_mini_005fuser_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:user
    com.tenwa.leasing.tag.GetUser _jspx_th_mini_005fuser_005f0 = (com.tenwa.leasing.tag.GetUser) _005fjspx_005ftagPool_005fmini_005fuser_005fnobody.get(com.tenwa.leasing.tag.GetUser.class);
    _jspx_th_mini_005fuser_005f0.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fuser_005f0.setParent(null);
    int _jspx_eval_mini_005fuser_005f0 = _jspx_th_mini_005fuser_005f0.doStartTag();
    if (_jspx_th_mini_005fuser_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fuser_005fnobody.reuse(_jspx_th_mini_005fuser_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fuser_005fnobody.reuse(_jspx_th_mini_005fuser_005f0);
    return false;
  }
}
