<%@ page language="java" contentType="text/html; charset=UTF-8"	pageEncoding="UTF-8"%>
<script type="text/javascript">
jQuery(function() {
		seajs.use([ "js/apcomponent/aptable/aptable.js" ], function(ApTable) {
			new ApTable({
				id:'loan_atm_plan',
				renderTo:'id_table_loan_atm_plan',
				width:globalClientWidth,
				height:globalClientHeight,
				title:'',
				iconCls:'icon-node',
				multiSelect:false,
				hiddenQueryArea:false,//是否将查询区域折叠起来
				queryButtonColSpan:2,
				queryButtonNewLine:false,
				showPager:true,
  				remoteOper:true,
  				params:{loanid:'${param.loanid}'},
				entityClassName:'com.tenwa.leasing.entity.finacial.LoanAtmPlan',
				xmlFileName:'/eleasing/jsp/finacial/loan_fee_plan/loan_atm_plan_list.xml',
				tools:['add','-','edit','-','remove'],
				columns:[ 
				    {type:'indexcolumn'},
				   	{type:'checkcolumn'},  
				   	{field:'id',header:'id',visible:false},
				   	{field:'loancontractid',header:'借款合同号',visible:true,allowSort:true,formEditorConfig:{
              			type:'text',
              			defaultValue:'${param.loancontractid}',
              			fieldVisible:true,
              			readOnly:true
              		}},
				   	{field:'loanid',header:'借款合同号',visible:false,allowSort:true,formEditorConfig:{
				   		required:true,
				   		fieldVisible:false,
				   		defaultValue:'${param.loanid}',
              			type:'text'
              		}}, 
				   	{field:'plandate',header:'提款日期',visible:true,formEditorConfig:{
				   		required:true,
				   		type:'date'
				   	}},
				   	{field:'planmoney',header:'提款金额',visible:true,dataType:'currency',formEditorConfig:{
				   		required:true,
				   		vtype:'float',
				   		newLine:true,
				   		fieldVisible:true
				   	}},
				   	{field:'accbank',header:'提款银行',visible:true,formEditorConfig:{
				   		required:true,
				   		vtype:'text',
				   		newLine:false,
				   		fieldVisible:true
				   	}},
				   	{field:'accname',header:'提款账户',visible:true,formEditorConfig:{
				   		required:true,
				   		vtype:'text',
				   		newLine:true,
				   		fieldVisible:true
				   	}},
				   	{field:'accnumber',header:'提款账号',visible:true,formEditorConfig:{
				   		required:true,
				   		vtype:'text',
				   		newLine:false,
				   		fieldVisible:true
				   	}},
				  {field:'memo',header:'备注',visible:true,formEditorConfig:{
				   		type:'textarea',
				   		newLine:true,
				   		colspan:'3',
				   		width:500
				   }}
				]
			});
		});
	});
</script>
</head>
<body>
	<div id="id_table_loan_atm_plan"></div>
</body>
</html>