	  var workFlowlocale =  {
			  step      : "step",
			  currentHandle : 'currentHandle',
			  WriteDate : 'WriteDate',
			  Add: "Add",
			  Edit: "Edit",
			  Remove: "Remove",
			  Copy : "Copy",
				confirm: "confirm",
				cancel: "cancel",
			  uploadTime : 'uploadTime',
			  uploadPerson : 'uploadPerson',
			  size:'size',
			  DownloadFile : 'DownloadFile',
			  NoDoc : 'No document',
			  fileIndex : 'fileIndex',
			  fileName : 'fileName',
			  Upload : 'Upload',
			  UploadAttachment : 'UploadAttachment',
			  UploadFileDetail : 'UploadFileDetail',
			  UploadFileDesc : 'UploadFileDesc',
			  DisableUpload  : 'Key is null </br>Can not upload file',
			  BatchDownloadFile : 'BatchDownloadFile',
			  NoInstructions : 'No instructions',
			  UploadTemplateNo : 'File upload module name cannot be empty',
			  shadeInfo : "The data load , Please wait...",
			  PictureShadeInfo : "The picture load , Please wait...",
			  removeShadeInfo : "The picture remove , Please wait...",
			  remove: "remove",
			  removeAttrInfo : 'Do you confirm to delete the attachment',
			  removePicInfo : 'Do you confirm to delete the picture',
			  UploadType : 'UploadType',
			  CurrentTime : 'CurrentTime',
			  ChooseFile : 'ChooseFile',
			  FileDesc : 'FileDesc',
			  FileUploadByOrder :  'please upload the attachment by the order!',
			  UploadProgress : 'UploadProgress',
			  StorageProgress : 'StorageProgress',
			  PictureDetails : 'PictureDetails(',
			  GetPictureFail : 'Failed to get image list',
			  UploadPicFail : 'Upload Fail',
			  UploadPicSucess : 'Upload Sucess',
			  RemovePicFail: 'Remove Fail',
			   RemovePicSucess : 'Remove Sucess'
	};

