/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-02-08 08:28:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.fund.fund_005fput;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fund_005fput_005fcurrent_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\t//获取父页面中保存在hidden域的值\r\n");
      out.write("\tvar showTools = true;\r\n");
      out.write("\tif('<mini:param  name=\"isView\"/>' == 'true'||isViewHistoryTask==true){showTools = false;};\r\n");
      out.write("\tseajs.use([ \"js/apcomponent/aptable/aptable.js\" ], function(ApTable) {\r\n");
      out.write("\t\tnew ApTable({\r\n");
      out.write("\t\tid: \"put_current\",\r\n");
      out.write("\t\trenderTo: \"id_table_put_current\",\r\n");
      out.write("\t\twidth : globalClientWidth-10,\r\n");
      out.write("\t\theight : 300,\r\n");
      out.write("\t\teditFormPopupWindowWidth : 600,\r\n");
      out.write("\t\tlazyLoad: false,\r\n");
      out.write("\t\tisClickLoad:false,\r\n");
      out.write("\t\ttitle: \"\",\r\n");
      out.write("\t\tremoteOper : false,\r\n");
      out.write("\t\tshowPager: false,\r\n");
      out.write("\t\tshowToolbar: showTools,\r\n");
      out.write("\t\tmultiSelect: true,\r\n");
      out.write("\t\ttools: ['edit','-','copy','-','remove','-',{\r\n");
      out.write("\t\t\thtml : '批量修改本方银行账号',\r\n");
      out.write("\t\t\tplain : true,\r\n");
      out.write("\t\t\ticonCls : 'icon-save',   \r\n");
      out.write("\t\t\thandler : function(miniTable, buttonText) {\r\n");
      out.write("\t\t\t\tmini.get(\"id_select_pay_account\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t'-',{\r\n");
      out.write("\t\t\thtml : '删除本方银行账号',\r\n");
      out.write("\t\t\tplain : true,\r\n");
      out.write("\t\t\ticonCls : 'icon-save',   \r\n");
      out.write("\t\t\thandler : function(miniTable, buttonText) {\r\n");
      out.write("\t\t\t\tdeleteFundPayCountInfo();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}],\r\n");
      out.write("\t\tvalidateForm: function(miniTable, miniForm){\r\n");
      out.write("\t\t\tvar comparemoney =getMiniEditFormField(\"put_current.comparemoney\").getValue();\r\n");
      out.write("\t\t\tvar factmoney =getMiniEditFormField(\"put_current.factmoney\").getValue();\r\n");
      out.write("\t\t\tcomparemoney=parseFloat(comparemoney).toFixed(2);\r\n");
      out.write("\t\t\tfactmoney=parseFloat(factmoney).toFixed(2);\r\n");
      out.write("\t\t\tif (parseFloat(comparemoney) < parseFloat(factmoney))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tmini.alert(\"本次投放金额不能大于计划可投放金额!(\"+comparemoney+\")\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tremoveOperCallBack:function(miniTable, rowDatas){\r\n");
      out.write("\t           var guarantable=mini.get(\"caution_money_refund_detail\");\r\n");
      out.write("\t           var guarantableData=guarantable.getData();\r\n");
      out.write("\t\t\t   for(j=0;j<rowDatas.length;j++){\r\n");
      out.write("\t               var pid=rowDatas[j].pid;              \r\n");
      out.write("\t               for(var i=0;i<guarantableData.length;i++){\r\n");
      out.write("\t                    if(guarantableData[i].fundfundchargeplan==pid){\r\n");
      out.write("\t                    \tguarantable.removeRow (guarantableData[i]);\r\n");
      out.write("\t                    }\r\n");
      out.write("\t               }\t               \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t   guarantable=mini.get(\"rent_income_detail\");\r\n");
      out.write("\t           guarantableData=guarantable.getData();\r\n");
      out.write("\t\t\t   for(j=0;j<rowDatas.length;j++){\r\n");
      out.write("\t               var pid=rowDatas[j].pid;              \r\n");
      out.write("\t               for(var i=0;i<guarantableData.length;i++){\r\n");
      out.write("\t                    if(guarantableData[i].planid==pid){\r\n");
      out.write("\t                    \tguarantable.removeRow (guarantableData[i]);\r\n");
      out.write("\t                    }\r\n");
      out.write("\t               }\t               \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t       return true;\r\n");
      out.write("\t    },\r\n");
      out.write("\t\tdata: JsonUtil.decode('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_put_current_str ? \"[]\" : json_put_current_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'),\r\n");
      out.write("\t\tcolumns: [\r\n");
      out.write("\t\t\t{type: 'indexcolumn'},\r\n");
      out.write("\t\t\t{type: 'checkcolumn'},\r\n");
      out.write("\t\t\t{field: 'id', header: 'id', visible: false},\r\n");
      out.write("\t\t\t{field: 'pid', header: 'pid', visible: false},\r\n");
      out.write("\t\t\t{field:'fundfundchargeplan',header:'付款计划',visible: false},\r\n");
      out.write("\t\t\t{field: 'paymentid', header: '付款编号',formEditorConfig:{readOnly : true}}, \r\n");
      out.write("\t\t\t{field: 'comparemoney', header: '比较金额', visible: false,formEditorConfig:{readOnly : true}}, \r\n");
      out.write("\t\t\t{field: 'feetype', header: '费用类型',formEditorConfig:{}, visible: false},\r\n");
      out.write("\t\t\t{field: 'feetypename', header: '费用类型',formEditorConfig:{readOnly : true}},\r\n");
      out.write("\t\t\t{field: 'paytype', header: '支付类型',formEditorConfig:{newLine:true}, visible: false},\r\n");
      out.write("\t\t\t{field: 'paytypename', header: '支付类型', visible: false,formEditorConfig:{newLine:true,readOnly:true}},\r\n");
      out.write("\t\t\t{field: 'factobjectname', header: '支付对象',formEditorConfig:{fieldVisible: false}},\r\n");
      out.write("\t\t\t{field: 'factobject', header: '支付对象',visible: false,formEditorConfig:{\r\n");
      out.write("\t\t\t\tnewLine: true,\r\n");
      out.write("\t\t\t\ttype : 'queryinput',\r\n");
      out.write("\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\ttextField: 'name',\r\n");
      out.write("\t\t\t\tvalueField: 'name',\r\n");
      out.write("\t\t\t\tallowInput: false,\r\n");
      out.write("\t\t\t\tfieldVisible: true,\r\n");
      out.write("\t\t\t\tcolspan:3,\r\n");
      out.write("\t\t\t\tonSelect:function(){clearCustbank();},\r\n");
      out.write("\t\t\t\tparams: {\r\n");
      out.write("\t\t\t\t\txmlFileName: 'common/custInfo.xml'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{field: 'factmoney', header: '投放金额',summary : true,dataType : \"currency\",formEditorConfig:{newLine:true,required: true}},\r\n");
      out.write("\t\t\t{field: 'settlemethod', header: '结算方式', visible: false,formEditorConfig:{\r\n");
      out.write("\t\t\t\ttype : 'combobox',\r\n");
      out.write("\t\t\t\trequired: true,\r\n");
      out.write("\t\t\t\ttextField: 'name',\r\n");
      out.write("\t\t\t\tvalueField: 'value',\r\n");
      out.write("\t\t\t\tallowInput: true,\r\n");
      out.write("\t\t\t\tfieldVisible: true,\r\n");
      out.write("\t\t\t\tcolspan : 3,\t\r\n");
      out.write("\t\t\t\tparams: {\r\n");
      out.write("\t\t\t\t     pid: 'PayFund',\r\n");
      out.write("\t\t\t\t\t xmlFileName: 'combos/comboDict.xml'\t\r\n");
      out.write("\t\t\t\t}}},\r\n");
      out.write("\t\t\t{field: 'settlemethodname', header: '结算方式',formEditorConfig:{fieldVisible: false,\r\n");
      out.write("\t\t\t\t  fillFromFieldName : 'settlemethod',\r\n");
      out.write("\t\t\t\tfillProperty : 'name'}},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t{field: 'factdate', header: '投放日期',formEditorConfig:{newLine:true,required: true,type:'date'}},\r\n");
      out.write("\t\t\t{field: 'accountingdate', header: '会计处理日',formEditorConfig:{type:'date'}},\r\n");
      out.write("\t\t\t{field: 'accountbankname', header: '对方银行',visible: false,formEditorConfig:{\r\n");
      out.write("\t\t\t\tfillFromFieldName : 'accountbank',\r\n");
      out.write("\t\t\t\tfillProperty : 'accbank'}},\r\n");
      out.write("\t\t\t{field: 'accountbank', header: '本方银行',\r\n");
      out.write("\t\t\t\tformEditorConfig:\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tnewLine:true,\r\n");
      out.write("\t\t\t\t\ttype : 'combobox', \r\n");
      out.write("\t\t\t\t\tmultiSelect : false, \r\n");
      out.write("\t\t\t\t\tvalueField : 'accbank', \r\n");
      out.write("\t\t\t\t\ttextField : 'accbank', \r\n");
      out.write("\t\t\t\t\tlabelWidth : 100, \r\n");
      out.write("\t\t\t\t\twidth : 200, \r\n");
      out.write("\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\txmlFileName : 'eleasing/jsp/sysmgr/sysdatamgr/ownaccountinfo.xml'\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},   \r\n");
      out.write("\t\t\t{field: 'account', header: '本方账户',\r\n");
      out.write("\t\t\t\tformEditorConfig:{\r\n");
      out.write("\t\t\t\t\tfillFromFieldName : 'accountbank',\r\n");
      out.write("\t\t\t\t\tfillProperty : 'accname',\r\n");
      out.write("\t\t   \t\t\treadonly:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{field: 'accnumber', header: '本方账号',\r\n");
      out.write("\t\t\t\tformEditorConfig:{\r\n");
      out.write("\t\t\t\t\tfillFromFieldName : 'accountbank',\r\n");
      out.write("\t\t\t\t\tfillProperty : 'accnumber',\r\n");
      out.write("\t\t   \t\t\treadonly:true,\r\n");
      out.write("\t\t   \t\t\tnewLine:true,\r\n");
      out.write("\t\t   \t\t\tcolspan : 3\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{field: 'clientbankname', header: '对方银行',visible: false,formEditorConfig:{\r\n");
      out.write("\t\t\tfillFromFieldName : 'clientbank',\r\n");
      out.write("\t\t\tfillProperty : 'clientbank'}},\r\n");
      out.write("\t\t\t{field: 'clientbank', header: '对方银行',\r\n");
      out.write("\t\t\t\tformEditorConfig:\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tnewLine:true,\r\n");
      out.write("\t\t\t\t\ttype : 'combobox',\r\n");
      out.write("\t\t\t\t\trequired : true,\r\n");
      out.write("\t\t\t\t\tmultiSelect : false, \r\n");
      out.write("\t\t\t\t\tvalueField : 'clientbank',\r\n");
      out.write("\t\t\t\t\ttextField : 'clientbank',\r\n");
      out.write("\t\t\t\t\tlabelWidth : 100,\r\n");
      out.write("\t\t\t\t\twidth : 200,\r\n");
      out.write("\t\t\t\t\tonclick:'initCustbank',\r\n");
      out.write("\t\t\t\t\tonbuttonclick:'initCustbank',\r\n");
      out.write("\t\t\t\t\tlazyLoad: true,\r\n");
      out.write("\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\txmlFileName : 'common/custbankInfo.xml',\r\n");
      out.write("\t\t\t\t\t\tcustname:'xxxxx'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{field: 'clientaccount', header: '对方账户',\r\n");
      out.write("\t\t\t\tformEditorConfig:{\r\n");
      out.write("\t\t\t\t\tfillFromFieldName : 'clientbank',\r\n");
      out.write("\t\t\t\t\tfillProperty : 'clientaccount',\r\n");
      out.write("\t\t   \t\t\treadonly:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{field: 'clientaccnumber', header: '对方账号',\r\n");
      out.write("\t\t\t\tformEditorConfig:{\r\n");
      out.write("\t\t\t\t\tfillFromFieldName : 'clientbank',\r\n");
      out.write("\t\t\t\t\tfillProperty : 'clientaccnumber',\r\n");
      out.write("\t\t   \t\t\treadonly:true,\r\n");
      out.write("\t\t   \t\t\tnewLine:true,\r\n");
      out.write("\t\t   \t\t\tcolspan : 3\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{field: 'ffcmemo', header: '备注',formEditorConfig:{\r\n");
      out.write("\t\t\t\ttype: 'textarea',\r\n");
      out.write("\t\t\t\tnewLine:true,\r\n");
      out.write("\t\t\t\tcolspan : 3,\r\n");
      out.write("\t\t\t\twidth: 400,\r\n");
      out.write("\t\t\t\theight:70\r\n");
      out.write("\t\t\t}}\r\n");
      out.write("\r\n");
      out.write("\t\t]\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t \r\n");
      out.write("});\r\n");
      out.write("function initCustbank(){\r\n");
      out.write("    var factobj=getMiniEditFormField(\"put_current.factobject\");\r\n");
      out.write("    var clientbank=getMiniEditFormField(\"put_current.clientbank\");\r\n");
      out.write("    fact=factobj.getText();\r\n");
      out.write("    if(fact==\"\"){alert(\"请选择付款对象\");return false;}\r\n");
      out.write("    var param={};\r\n");
      out.write("    param[\"custname\"]=fact;\r\n");
      out.write("    param[\"xmlFileName\"]=\"common/custbankInfo.xml\",\r\n");
      out.write("    seajs.use([ \"js/apcomponent/aputil/aputil.js\" ],function(ApUtil){\r\n");
      out.write("    \t ApUtil.setComboxParams(clientbank,param);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function checkFundPutInfo()\r\n");
      out.write("{\t\r\n");
      out.write("\tvar put_current_value = mini.get(\"id_json_put_current_str\").getValue();\r\n");
      out.write("\tvar put_current_data =  mini.decode(put_current_value);\r\n");
      out.write("\tvar chargeData= mini.get(\"put_current\").isinitData==1 ? \r\n");
      out.write("\t\t\tmini.get(\"put_current\").getData() : put_current_data;\r\n");
      out.write("\tif( put_current.length == 0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmini.alert(\"本次投放明细不能为空!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function clearCustbank(){\r\n");
      out.write("\tgetMiniEditFormField(\"put_current.clientaccount\").setValue(\"\");\r\n");
      out.write("\tgetMiniEditFormField(\"put_current.clientaccnumber\").setValue(\"\");\r\n");
      out.write("\tgetMiniEditFormField(\"put_current.clientbank\").setValue(\"\");\r\n");
      out.write("\tgetMiniEditFormField(\"put_current.clientbank\").setText(\"\");\r\n");
      out.write("}\r\n");
      out.write("//检查抵扣的金额和被抵扣金额是不是一样\r\n");
      out.write("function CheckDecdueMoney(){\r\n");
      out.write("   var payData=mini.get(\"put_current\").getData();\r\n");
      out.write("   var fundData=mini.get(\"caution_money_refund_detail\").getData();\r\n");
      out.write("   var rentData=mini.get(\"rent_income_detail\").getData();\r\n");
      out.write("   if(payData.length>0){\r\n");
      out.write("       for(var i=0;i<payData.length;i++){\r\n");
      out.write("            for(var j=0;j<fundData.length;j++){\r\n");
      out.write("                if(payData[i].pid==fundData[j].fundfundchargeplan&&(parseFloat(payData[i].factmoney)!=parseFloat(fundData[j].factmoney))){\r\n");
      out.write("                    mini.alert(\"设备款(\"+payData[i].factmoney+\")与被抵扣的\"+fundData[j].feetypename+\"(\"+fundData[j].factmoney+\")不一样\");\r\n");
      out.write("                      return false;\r\n");
      out.write("                 }\r\n");
      out.write("            }\r\n");
      out.write("            for(var h=0;h<rentData.length;h++){\r\n");
      out.write("            \t   if(payData[i].pid==rentData[h].planid&&(parseFloat(payData[i].factmoney)!=parseFloat(rentData[h].rent))){\r\n");
      out.write("                       mini.alert(\"设备款(\"+payData[i].factmoney+\")与被抵扣的租金(\"+rentData[h].rent+\")不一样\");\r\n");
      out.write("                         return false;\r\n");
      out.write("                    }\r\n");
      out.write("            }\r\n");
      out.write("       }\r\n");
      out.write("       return true;\r\n");
      out.write("   }else{\r\n");
      out.write("     return true;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"id_table_put_current\"></div>\r\n");
      out.write(" <div id=\"id_select_pay_account\" class=\"mini-window\"   closed=\"true\" modal=\"true\" title=\"选择支付对象和银行账号\" style=\"display:none;width:350px;padding-top:20px;\">\r\n");
      out.write("       <table lass=\"fillTable\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" >\r\n");
      out.write("              <tr class=\"tr-pay_account tr-even\" style=\"height:40px\">\r\n");
      out.write("\t           <td class=\"td-content-title\" width=\"25%\">会计处理日：</td>\r\n");
      out.write("\t             <td class=\"td-content\">\r\n");
      out.write("                      <input id=\"id_select_data\" name=\"selectdata\" label=\"会计处理日\" class=\"mini-datepicker\" allowInput=\"false\" required=\"true\"/>\r\n");
      out.write("\t\t\t\t\t <font class=\"required-tag\">*</font>\r\n");
      out.write("                 </td>\r\n");
      out.write("\t          </tr  >\r\n");
      out.write("\t          <tr class=\"tr-project-info tr-even\" style=\"height:40px\">\r\n");
      out.write("\t          <td class=\"td-content-title\" width=\"25%\">本方银行：</td>\r\n");
      out.write("\t              <td class=\"td-content\" > <input id=\"id_select_bank\" name=\"selectbank\"   class=\"mini-combobox\"  label=\"对方银行\"  required=\"true\" allowInput=\"false\"/>\r\n");
      out.write("\t              <font class=\"required-tag\">*</font></td>\r\n");
      out.write("\t          </tr >\r\n");
      out.write("\t          <tr class=\"tr-project-info tr-even\" style=\"height:40px\">\r\n");
      out.write("\t          <td class=\"td-content-title\" width=\"25%\">本方账户：</td>\r\n");
      out.write("\t             <td class=\"td-content\" > <input id=\"id_select_account\" name=\"selectaccount\" class=\"mini-textbox\"  readOnly  label=\"对方账户\"  required=\"true\" allowInput=\"false\"/> <font class=\"required-tag\">*</font></td>\r\n");
      out.write("\t          </tr>\r\n");
      out.write("\t          <tr  class=\"tr-project-info tr-even\" style=\"height:40px\">\r\n");
      out.write("\t          <td class=\"td-content-title\" width=\"25%\">本方账号：</td>\r\n");
      out.write("\t             <td class=\"td-content\" > <input id=\"id_select_accnumber\" name=\"selectaccnumber\" class=\"mini-textbox\"   readOnly  label=\"对方账号\"  required=\"true\" allowInput=\"false\"/> <font class=\"required-tag\">*</font> </td>\r\n");
      out.write("\t          </tr >\r\n");
      out.write("               <tr class=\"content-separator\">                 \r\n");
      out.write("\t\t\t\t      <td colspan='2' align=\"center\">\r\n");
      out.write("\t\t\t\t           <a  style=\"margin-left:20px;\"  class=\"mini-button\" iconCls=\"icon-add\" onclick='setFundPutInfo();'><span>确定</span></a>\r\n");
      out.write("\t\t\t\t\t\t   <a  style=\"margin-left:20px;\"  class=\"mini-button\" iconCls=\"icon-close\" onclick='mini.get(\"id_select_pay_account\").hide();'><span>取消</span></a>\r\n");
      out.write("\t\t\t\t      </td>\r\n");
      out.write("\t\t\t   </tr>\r\n");
      out.write("       </table>\r\n");
      out.write(" </div>\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\tif('<mini:param  name=\"isView\"/>' == 'true' || isViewHistoryTask==true){\r\n");
      out.write("\t}else{\t\r\n");
      out.write("\t            var param={};\r\n");
      out.write("\t            param[\"xmlFileName\"]=\"eleasing/jsp/sysmgr/sysdatamgr/ownaccountinfo.xml\";\r\n");
      out.write("\t      \t    ajaxRequest({\r\n");
      out.write("\t      \t      url:getRootPath()+'/table/getTableData.action',\r\n");
      out.write("\t      \t      async:false,\r\n");
      out.write("\t      \t      params:param,\r\n");
      out.write("\t      \t      timeout:60*60*1000,\r\n");
      out.write("\t      \t      success:function(res){\r\n");
      out.write("\t      \t          var currentData = mini.decode(res.responseText);\r\n");
      out.write("\t      \t          var cdata=mini.decode(currentData.datas);\r\n");
      out.write("\t      \t          mini.get('id_select_bank').set({\r\n");
      out.write("\t\t\t\t\t\ttextField : \"accbank\",\r\n");
      out.write("\t\t\t\t\t\tvalueField : \"accbank\",\r\n");
      out.write("\t\t\t\t\t\tdata:cdata,\t\r\n");
      out.write("\t\t\t\t\t\tonValueChanged:function(){\r\n");
      out.write("\t\t\t\t\t\t\tvar selecteds = this.getSelecteds();\r\n");
      out.write("\t\t\t\t\t        var selected = selecteds[0];//单选只有一个\r\n");
      out.write("\t\t\t\t\t\t\tmini.get(\"id_select_account\").setValue(selected.accname);\r\n");
      out.write("\t\t\t\t\t\t\tmini.get(\"id_select_accnumber\").setValue(selected.accnumber);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t });\r\n");
      out.write("\t      \t      }});    \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("});\r\n");
      out.write("function setFundPutInfo(){\r\n");
      out.write("\t var curTable=mini.get(\"put_current\")\r\n");
      out.write("\t var payData=curTable.getData();\r\n");
      out.write("\t var selectData=curTable.getSelecteds();\r\n");
      out.write("\t var paydata=mini.formatDate(mini.get(\"id_select_data\").getValue(),\"yyyy-MM-dd\");\r\n");
      out.write("\t var paybank=mini.get(\"id_select_bank\").getValue();\r\n");
      out.write("\t var payaccount=mini.get(\"id_select_account\").getValue();\r\n");
      out.write("\t var payaccnumber=mini.get(\"id_select_accnumber\").getValue();\r\n");
      out.write("\t if(selectData.length>0){\r\n");
      out.write("\t\t for(var i=0;i<selectData.length;i++){\r\n");
      out.write("\t\t\t var cm={\"accountingdate\":paydata,\"accountbankname\":paybank,\"accountbank\":paybank,\"account\":payaccount,\"accnumber\":payaccnumber}\r\n");
      out.write("\t\t\t if(selectData[i].settlemethodname==\"货扣\"){\r\n");
      out.write("\t\t\t\t cm={\"accountingdate\":paydata};\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t curTable.updateRow(selectData[i],cm);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }else{\r\n");
      out.write("\t    for(var i=0;i<payData.length;i++){\r\n");
      out.write("\t    \tvar cm={\"accountingdate\":paydata,\"accountbankname\":paybank,\"accountbank\":paybank,\"account\":payaccount,\"accnumber\":payaccnumber}\r\n");
      out.write("\t\t\t if(payData[i].settlemethodname==\"货扣\"){\r\n");
      out.write("\t\t\t\t cm={\"accountingdate\":paydata};\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t    \t curTable.updateRow(payData[i],cm);\r\n");
      out.write("\t    }\r\n");
      out.write("\t }\r\n");
      out.write("\t curTable.deselectAll();\r\n");
      out.write("\t mini.get(\"id_select_pay_account\").hide();\r\n");
      out.write("}\r\n");
      out.write("function deleteFundPayCountInfo(){\r\n");
      out.write("\tvar curTable=mini.get(\"put_current\")\r\n");
      out.write("\tvar payData=curTable.getData();\r\n");
      out.write("\tvar cm={\"accountbankname\":\"\",\"accountbank\":\"\",\"account\":\"\",\"accnumber\":\"\"}\r\n");
      out.write("\tvar selectData=curTable.getSelecteds();\r\n");
      out.write("\tif(selectData.length>0){\r\n");
      out.write("\t    for(var i=0;i<selectData.length;i++){\r\n");
      out.write("\t\t\t curTable.updateRow(selectData[i],cm);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t}else{\r\n");
      out.write("\tfor(var i=0;i<payData.length;i++){\r\n");
      out.write("\t\tcurTable.updateRow(payData[i],cm);\r\n");
      out.write("    }}\r\n");
      out.write("\t curTable.deselectAll();\r\n");
      out.write("\t mini.alert(\"操作成功\");\r\n");
      out.write("}\r\n");
      out.write("function checkFundPayAccount(){\r\n");
      out.write("\t var payData=mini.get(\"put_current\").getData();\r\n");
      out.write("\t var message=[];\r\n");
      out.write("\t var payObj=\"\";\r\n");
      out.write("\t var clientbankname=\"\";\r\n");
      out.write("\t var paytype=\"\";\r\n");
      out.write("\t if(payData.length>0){\r\n");
      out.write("\t\t for(var i=0;i<payData.length;i++){\r\n");
      out.write("\t\t\t pay=payData[i].accountingdate||\"\";\r\n");
      out.write("\t\t\t clientbankname=payData[i].accountbankname||\"\";\r\n");
      out.write("\t\t\t paytype=payData[i].settlemethodname||\"\";\r\n");
      out.write("\t\t\t if(paytype==\"货扣\"){\r\n");
      out.write("\t\t\t\t if(pay==\"\"){\r\n");
      out.write("\t\t\t\t\t message.push(\"设备款[\"+payData[i].factmoney+\"]会计处理日没填<br>\");\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t if(pay==\"\"||clientbankname==\"\"){\r\n");
      out.write("\t\t\t\t message.push(\"设备款[\"+payData[i].factmoney+\"]会计处理日或本方银行没有填<br>\");\r\n");
      out.write("\t\t\t }}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t if(message.length>0){\r\n");
      out.write("\t\t\t mini.alert(message,\"本次投放明细\");\r\n");
      out.write("\t\t\t selectChangeTab(\"tabApprovalDeatils\",\"put_current\");\r\n");
      out.write("\t\t\t return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("\t return true;\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
