/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-06-16 08:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.rent.rent_005fincome;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ebank_005fimport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t<div id=\"ebank_import_form\">\r\n");
      out.write("\t\t<input name=\"fund_ebank_data.id\" id=\"fund_ebank_data.id\" class=\"mini-hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.id']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t<table class=\"fillTable\" cellspacing=\"0\" cellpadding=\"0\" id=\"ebank_import_table\">\r\n");
      out.write("\t\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">网银编号：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.ebdataid\" name=\"fund_ebank_data.ebdataid\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.ebdataid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">付款人：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.clientname\" name=\"fund_ebank_data.clientname\" class=\"mini-textbox\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.clientname']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">流水号：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.sn\" name=\"fund_ebank_data.sn\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.sn']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">本方银行：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.ownbank\" name=\"fund_ebank_data.ownbank\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.ownbank']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">本方账户：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.ownaccount\" name=\"fund_ebank_data.ownaccount\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.ownaccount']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">本方账号：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.ownaccnumber\"  name=\"fund_ebank_data.ownaccnumber\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.ownaccnumber']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">对方银行：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.clientbank\" name=\"fund_ebank_data.clientbank\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.clientbank']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">对方账户：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.clientaccount\" name=\"fund_ebank_data.clientaccount\" class=\"mini-textbox\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.clientaccount']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">对方账号：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.clientaccnumber\" name=\"fund_ebank_data.clientaccnumber\" class=\"mini-textbox\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.clientaccnumber']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">到账金额：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.factmoney\" name=\"fund_ebank_data.factmoney\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.factmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">已核销金额：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\" ><input id=\"fund_ebank_data.hadmoney\" name=\"fund_ebank_data.hadmoney\" class=\"mini-textbox\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.hadmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">可核销金额：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\" ><input id=\"fund_ebank_data.mayopemoney\" name=\"fund_ebank_data.mayopemoney\" class=\"mini-textbox\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.mayopemoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">无关金额：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.nowithmoney\" name=\"fund_ebank_data.nowithmoney\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.nowithmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">到账金额类型：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.moneytype\" name=\"fund_ebank_data.moneytype\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.moneytype']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">到账时间：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\"><input id=\"fund_ebank_data.factdate\" name=\"fund_ebank_data.factdate\" class=\"mini-textbox\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.factdate']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content-title\">备注：</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"width:87%;height: 80px;\" id=\"fund_ebank_data.summary\" name=\"fund_ebank_data.summary\"  required=\"true\" label=\"备注\" class=\"mini-textarea\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_ebank_data.summary'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"td-content\" colspan=\"3\" style=\"text-indent: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"auto_hire\" class=\"mini-button\" onclick=\"hireRent()\" style=\"color: red;font-weight: bold;\">自动核销</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\tvar showTools = true;\r\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.isView}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' == 'true'||isViewHistoryTask==true){showTools = false;};\r\n");
      out.write("    if(showTools==false){\r\n");
      out.write("         mini.get(\"auto_hire\").hide();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("function hireRent(){\r\n");
      out.write("\tvar maymoney=getfundEbankOverMoney();//获得网银余额（网银余额-已增加到每次核销的租金）\r\n");
      out.write("\tvar planTable=mini.get(\"rent_income_plan\");\r\n");
      out.write("\tvar currTable = mini.get(\"rent_income_detail\");\r\n");
      out.write("\tvar currRowDatas = mini.clone(currTable.getData());\r\n");
      out.write("\tvar selectedDatas = planTable.getData();\r\n");
      out.write("\tgenerateRentDetail(planTable,currTable,currRowDatas,selectedDatas,maymoney);\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
