var workFlowlocale = {
		step      : "步骤",
		currentHandle : '当前处理',
		WriteDate : '填写时间',
		Edit : '编辑',
		Add : '新增',
		Confirm : "确&nbsp;认",
		Cancel : "取&nbsp;消",
		Remove : "删除",
		Copy : "复制",
		 confirm : "确&nbsp;认",
		 cancel : "取&nbsp;消",
		uploadTime : '上传日期',
		uploadPerson : '上传人',
		size:'大小',
		DownloadFile : '下载文件',
		NoDoc : '暂无文档' ,
		fileIndex : '文件编号',
		fileName : '文件名称',
		Upload : '上载',
		UploadAttachment : '附件上传',
		UploadFileDetail : '上载文件清单',
		UploadFileDesc : '文件说明',
		DisableUpload : '关键字为空</br>不能上载文件',
		BatchDownloadFile : "批量下载文件",
		NoInstructions : '暂无说明',
		UploadTemplateNo : '文件上传的模块名称不能为空',
		shadeInfo : "数据加载中 请稍等...",
		removeShadeInfo : "数据删除中 请稍等...",
		PictureShadeInfo : "图片上传中，请稍后...",
		remove : "删除",
		removeAttrInfo : '确定删除该附件么',
		removePicInfo : '确定要删除改图片么',
		UploadType : '上传类型',
		CurrentTime : '当前时间',
		ChooseFile : '文件选择',
		FileDesc : '文件说明',
		FileUploadByOrder: '请按照顺序上传附件',
		UploadProgress : '上传进度',
		StorageProgress : '存储进度',
		PictureDetails : '图片明细（',
		GetPictureFail : '获取图片列表失败',
		UploadPicFail: '图片上传失败！',
		UploadPicSucess: '图片上传成功！',
		RemovePicSucess: '删除图片成功！',
		RemovePicFail: '删除图片失败！',
		UploadActivity : "上传步骤"
	};