/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-04-02 15:09:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.solutions.report;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class history_005fdata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/tlds/spring.tld", Long.valueOf(1486341662563L));
    _jspx_dependants.put("/base/base.jsp", Long.valueOf(1486341528500L));
    _jspx_dependants.put("/base/var.jsp", Long.valueOf(1486341528493L));
    _jspx_dependants.put("/WEB-INF/tlds/minidict.tld", Long.valueOf(1486341662546L));
    _jspx_dependants.put("/base/mini.jsp", Long.valueOf(1486341528509L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1486341662557L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fc_005fif_0026_005ftest != null) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    if (_005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody != null) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    if (_005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody != null) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    if (_005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody != null) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>1104报表历史数据查询</title>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar globalTimestamp = \"");
      if (_jspx_meth_mini_005fparam_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\tvar globalLocale = \"");
      if (_jspx_meth_mini_005fparam_005f1(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\tvar globalSkin = \"");
      if (_jspx_meth_mini_005fparam_005f2(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\tvar globalClientWidth = document.documentElement.clientWidth;\r\n");
      out.write("\tvar globalClientHeight = document.documentElement.clientHeight;\r\n");
      out.write("\tvar globalWebRoot = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\tvar urlPrefix = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/table/getTableData.action?tracywindyRandom=1&decorate=none&xmlFileName=\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/seajs/sea.js?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery-1.11.0.min.js?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">seajs.config({vars: { currentLocale: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentLocale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',currentSkin:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentSkin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'},base: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/',map: [[ /^(.*\\.(?:css|js))(.*)$/i, '$1?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' ]],charset: 'UTF-8'});</script>\r\n");
      out.write("<link rel=stylesheet href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/base/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentSkin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/base.css?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/miniui/miniui.js?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/miniui/locale/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentLocale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(".js?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/comm/miniui_ext.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/comm/miniuiExtButtons.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/comm/DataUtil.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=stylesheet href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/miniui/default/miniui.css?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<link rel=stylesheet href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/miniui/icons.css?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<link rel=stylesheet href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/miniui/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentSkin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/skin.css?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentTimestamp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<link rel=stylesheet href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/comm/miniui_ext.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction getRootPath() {\r\n");
      out.write("\t\tvar strFullPath = window.document.location.href;\r\n");
      out.write("\t\tvar strPath = window.document.location.pathname;\r\n");
      out.write("\t\tvar pos = strFullPath.indexOf(strPath);\r\n");
      out.write("\t\tvar prePath = strFullPath.substring(0, pos);\r\n");
      out.write("\t\tvar postPath = strPath.substring(0, strPath.substr(1).indexOf('/') + 1);\r\n");
      out.write("\t\treturn (prePath + postPath);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction miniextonbeforeshowpopup(e) {\r\n");
      out.write("\t\tminiui_ext.onbeforeshowpopup(e);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction miniextonDateRenderer(e){\r\n");
      out.write("\t\treturn miniui_ext.onDateRenderer(e);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction toggleFieldSet(ck, id) {\r\n");
      out.write("        var dom = document.getElementById(id);\r\n");
      out.write("        dom.className = !ck.checked ? \"hideFieldset\" : \"\";\r\n");
      out.write("        var _fit = mini.get(\"_fit\");\r\n");
      out.write("        _fit.setHeight(window.document.body.clientHeight);\r\n");
      out.write("    }\r\n");
      out.write("\tfunction CloseWindow(action) {            \r\n");
      out.write("\t\tif (action == \"close\" && grid.isChanged()) {\r\n");
      out.write("\t        if (confirm(\"æ°æ®è¢«ä¿®æ¹äºï¼æ¯å¦åä¿å­ï¼\")) {\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if (window.CloseOwnerWindow) return window.CloseOwnerWindow(action);\r\n");
      out.write("\t    else window.close();           \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onCancel(e) {\r\n");
      out.write("\t    CloseWindow(\"cancel\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onCloseClick(e) {\r\n");
      out.write("\t    var obj = e.sender;\r\n");
      out.write("\t    obj.setText(\"\");\r\n");
      out.write("\t    obj.setValue(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction isEnglish(){\r\n");
      out.write("\t\t if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userlanguage'].language}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == 'en'){\r\n");
      out.write("\t\t\t \treturn true;\r\n");
      out.write("         }\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction setapcolumnformatvalue(m){\r\n");
      out.write("\t\tvar obj = m.sender;\r\n");
      out.write("\t\tvar pMoneyOri = obj.getInputText().trim();\r\n");
      out.write("\t\tvar pMoney = pMoneyOri.replace(/,/gi,\"\");\r\n");
      out.write("\t\tif(pMoney==\"\"){pMoney = 0};\r\n");
      out.write("\t\tif(isNaN(pMoney)){\r\n");
      out.write("\t\t\t  pMoney=\"0\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if(pMoney.indexOf(\".\")>0){\r\n");
      out.write("\t    \tvar clen=pMoney.length-pMoney.indexOf(\".\");\r\n");
      out.write("\t    \tif(clen>=4){clen=3;}\r\n");
      out.write("\t    \tif(clen>1){\r\n");
      out.write("\t    \t\tpMoney=parseFloat(pMoney).toFixed(clen-1);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }\r\n");
      out.write("\t\tvar pMoneyReg = /^[-\\+]?\\d+[\\.]?([0-9]{1,2})?$/;\r\n");
      out.write("\t\tif(obj.vtype == 'rate'){\r\n");
      out.write("\t\t\tvar pMoneyReg = /^[-\\+]?\\d+[\\.]?([0-9]{1,6})?$/;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif((pMoneyOri && pMoneyOri.length>=0) && !pMoneyReg.test(pMoney)){\r\n");
      out.write("\t\t\tpMoney = 0;\r\n");
      out.write("\t\t\tobj.setValue();\r\n");
      out.write("\t\t\tobj.setValue('0');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tobj.setValue(formatNumberThousand(pMoney));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//æ ¼å¼åæ°å­ä¸ºååä½\r\n");
      out.write("\tfunction formatNumberThousand(s) {  \r\n");
      out.write("\t\ts += \"\";\r\n");
      out.write("\t\ts = s.replace(/,/g,\"\");\r\n");
      out.write("\t\tif(isNaN(s)){\r\n");
      out.write("\t\t return s;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ts += \"\";\r\n");
      out.write("\t\tvar re=/(\\d{1,3})(?=(\\d{3})+(?:$|\\D))/g; //\r\n");
      out.write("\t\tvar n1=s.replace(re,\"$1,\");\r\n");
      out.write("\t\treturn n1;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction thousandvalidation(e){\r\n");
      out.write("\t\t\t var temp= e.value.replace(/,/g,\"\");\r\n");
      out.write("\t\t\t if(temp==\"\"){return false;}\r\n");
      out.write("             if (temp.match(/^(:?(:?\\d+.\\d+)|(:?\\d+))$/)) {\r\n");
      out.write("            \t e.errorText = \"\";\r\n");
      out.write("                 e.isValid = true;\r\n");
      out.write("             }else{ \r\n");
      out.write("                 e.errorText = \"必须为数值\";\r\n");
      out.write("                 e.isValid = false;\r\n");
      out.write("                 e.value=0;\r\n");
      out.write("             }            \r\n");
      out.write("\t}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("   <div>\r\n");
      out.write("    \t<div class=\"mini-panel\" title=\"1104报表历史数据查询\" showCollapseButton=\"false\" style=\"width: 100%;\">    \t\r\n");
      out.write("    \t<div id=\"id_export_message\" style=\"display:none;text-align:center;width:90%;\">导出过程中请稍后.....</div>\r\n");
      out.write("\t\t    <a href=\"javascript:void(0);\" class=\"btn btn-primary\" style='border-radius:5px;float:right;margin-right:5px;'  onclick=\"doExport();\"><span>导出</span></a>\t\t    \r\n");
      out.write("\t\t    <a class='btn btn-primary'  style='float:right;border-radius:5px;margin-right:5px;' onclick=\"querysearch('implement')\">实时查询</a> \r\n");
      out.write("\t        <div class=\"fieldset-body\" id=\"form1\">\r\n");
      out.write("\t            <table class=\"miniext-form-table\" style=\"width:95%\">\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                <input name=\"buttondata\" id=\"buttondata\" style=\"display: none\" class=\"mini-textbox\" value=\"\"/>\r\n");
      out.write("\t                \t<td class=\"miniext-form-td\">报表分类：</td>\r\n");
      out.write("\t                    <td ><input id=\"reportclassify\" name=\"reportclassify\" class=\"mini-combobox miniext-form-fit\" textField=\"text\"  \r\n");
      out.write("\t                     valueField=\"value\"    data=\"[{text:'月报',value:'0'},{text:'季报',value:'1'},{text:'年报',value:'2'}]\"  \r\n");
      out.write("\t                      allowInput=\"false\"  onvaluechanged=\"onreportclassifychanged\"   /> </td>\r\n");
      out.write("\t                    <td class=\"miniext-form-td\">报表名称：</td>\r\n");
      out.write("\t\t                <td >\r\n");
      out.write("\t\t\t\t\t<input id=\"reportname\" name=\"reportname\" class=\"mini-combobox miniext-form-fit\"   allowInput=\"false\" \r\n");
      out.write("\t\t\t\t\t    textField=\"name\"   valueField=\"id\"  dataField=\"datas\"\r\n");
      out.write("\t\t\t\t\t    onbeforeshowpopup=\"onreportnamechanged\" />\r\n");
      out.write("\t\t               </td>\r\n");
      out.write("\t                    <td class=\"miniext-form-td\">年份：</td>\r\n");
      out.write("\t                     <td >\r\n");
      out.write("\t                <input  id=\"reportyear\" name=\"reportyear\" class=\"mini-datepicker miniext-form-fit\" format=\"yyyy\"/>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                </tr>   \r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td class=\"miniext-form-td\"  id=\"classify\">月份：</td>\r\n");
      out.write("\t                    <td>\r\n");
      out.write("\t                    <input id=\"reporttype\" name=\"reporttype\" class=\"mini-combobox miniext-form-fit\" textField=\"name\" \r\n");
      out.write("\t                  \t   valueField=\"value\"  \r\n");
      out.write("\t\t\t\t\t\t   allowInput=\"false\" \r\n");
      out.write("\t\t\t\t\t\t  />\r\n");
      out.write("\t                    </td>\r\n");
      out.write("\t                    <td colspan=\"4\">\r\n");
      out.write("\t                    \t<a class='mini-button query-button' iconCls='icon-search' onclick=\"querysearch\">搜索</a>\r\n");
      out.write("\t                    \t<!-- <a class='mini-button query-button' iconCls='icon-search' onclick=\"search('implement')\">实时查询</a> --> \r\n");
      out.write("\t                    \t<a  class='mini-button query-button' onclick=\"clear\" iconCls='icon-remove' style='color:#FFA5A5;border: 1px solid #FFA5A5;'>清空</a>\r\n");
      out.write("\t                    </td>\r\n");
      out.write("\t                </tr>  \r\n");
      out.write("\t            </table>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <!-- 按钮部分 -->\r\n");
      out.write("    <div id=\"miniuiextbuttons\"></div>\r\n");
      out.write("    <!--撑满页面-->\r\n");
      out.write("    <div class=\"mini-fit\"  id=\"list_view_div\">   \r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display:none\">\r\n");
      out.write("\t\t<iframe id=\"iframe_export\" src=\"about:blank\" style=\"display:none\">\t\t\r\n");
      out.write("\t\t</iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      mini.parse();\r\n");
      out.write("      var form = new mini.Form(\"form1\");\r\n");
      out.write("      function validationForm(){\r\n");
      out.write("    \t  var flag=false;\r\n");
      out.write("    \t  var reportclassify=mini.get(\"reportclassify\").getValue();\r\n");
      out.write("    \t  var reportname=mini.get(\"reportname\").getValue();\r\n");
      out.write("    \t  if(reportclassify!=''){\r\n");
      out.write("    \t\t    if(reportname==''){\r\n");
      out.write("    \t\t    \tmini.alert(\"请选择报表名称!\");\r\n");
      out.write("    \t    \t\t  flag=false;\r\n");
      out.write("    \t\t    }else{\r\n");
      out.write("    \t\t    \t flag=true;\r\n");
      out.write("    \t\t    }\r\n");
      out.write("    \t  }else{\r\n");
      out.write("   \t\t  mini.alert(\"请选择报表分类!\");\r\n");
      out.write("    \t\t  flag=false;\r\n");
      out.write("    \t  }\r\n");
      out.write("    \t  return flag;\r\n");
      out.write("      }\r\n");
      out.write("       function querysearch(e) {\r\n");
      out.write("    \t   if(!validationForm()){\r\n");
      out.write("    \t\t   return false;\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   var yearstr=mini.get(\"reportyear\").getValue();\r\n");
      out.write("    \t   var newyear='';\r\n");
      out.write("    \t   if(yearstr!=null||yearstr!=''){\r\n");
      out.write("    \t    newyear=mini.formatDate(yearstr, \"yyyy\");\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   var data = form.getData();\r\n");
      out.write("    \t    if(newyear!=null||newyear!=''){\r\n");
      out.write("    \t    \tdata.reportyear=newyear;\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t    if(e=='implement'){\r\n");
      out.write("    \t    \tdata.implement=e;\r\n");
      out.write("    \t    \tmini.get(\"buttondata\").setValue(e);//实时查询\r\n");
      out.write("    \t    }else{\r\n");
      out.write("    \t    \tmini.get(\"buttondata\").setValue(\"\");//历史查询\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t   $.ajax({\r\n");
      out.write("\t\t\t\turl:getRootPath()+\"/report/config/queryReportHisData.action\",\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tcache: false, \r\n");
      out.write("\t\t\t\tasync : false,\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t$(\"#list_view_div\").empty().append(result);\r\n");
      out.write("\t\t\t\t\t   mini.parse();\r\n");
      out.write("\t\t               var grid = mini.get(\"datagrid1\");\r\n");
      out.write("\t\t               var custData = form.getData(true,true);\r\n");
      out.write("\t\t               miniui_ext.addOnEnter(\"form1\");\r\n");
      out.write("\t\t               grid.load(custData);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("        }\r\n");
      out.write("        function clear(e) {\r\n");
      out.write("        \tform.clear();\r\n");
      out.write("        \tcustData = form.getData(true,true);\r\n");
      out.write(" \t\t    grid.load(custData);\r\n");
      out.write("        } \r\n");
      out.write("        var classify=mini.getbyName(\"reportclassify\").getValue();\r\n");
      out.write("        \r\n");
      out.write("    \tfunction onreportnamechanged(){\r\n");
      out.write("    \t    var reportnameCombo = mini.get(\"reportname\");\r\n");
      out.write("    \t    var url =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${urlPrefix}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/eleasing/jsp/report/report_tablename.xml&reportclassify=\"+classify;\r\n");
      out.write("    \t    reportnameCombo.setUrl(url);\r\n");
      out.write("    \t}\r\n");
      out.write("        //客户类型改变时动态获取\r\n");
      out.write("       var datas= new Array();\r\n");
      out.write("       function onreportclassifychanged(){\r\n");
      out.write("    \t  classify = mini.getbyName(\"reportclassify\").getValue();\r\n");
      out.write("    \t  mini.getbyName(\"reportname\").setText('');\r\n");
      out.write("    \t  mini.getbyName(\"reportname\").setValue('');\r\n");
      out.write("    \t  if(classify==0){ \r\n");
      out.write("    \t\t  $(\"#classify\").empty().append(\"月份\");\r\n");
      out.write("    \t\t  mini.getbyName(\"reporttype\").setData(\"[{value:'01',name:'1月'},{value:'02',name:'2月'},{value:'03',name:'3月'},{value:'04',name:'4月'},\"+\r\n");
      out.write("    \t\t                                        \" {value:'05',name:'5月'},{value:'06',name:'6月'},{value:'07',name:'7月'},{value:'08',name:'8月'},\"+\r\n");
      out.write("    \t\t                                        \" {value:'09',name:'9月'},{value:'10',name:'10月'},{value:'11',name:'11月'},{value:'12',name:'12月'}]\");\r\n");
      out.write("    \t  }else if (classify==1){\r\n");
      out.write("    \t\t  $(\"#classify\").empty().append(\"季度\");\r\n");
      out.write("    \t\t  mini.getbyName(\"reporttype\").setData(\"[{value:'03',name:'第一季度'},{value:'06',name:'第二季度'},{value:'09',name:'第三季度'},{value:'12',name:'第四季度'}]\");\r\n");
      out.write("    \t  }else if(classify==2){\r\n");
      out.write("    \t\t  $(\"#classify\").empty().append(\"上/下半年\");\r\n");
      out.write("    \t\t  mini.getbyName(\"reporttype\").setData(\"[{value:'06',name:'上半年'},{value:'12',name:'下半年'}]\");\r\n");
      out.write("    \t  }else{\r\n");
      out.write("    \t\t  $(\"#classify\").empty().append(\"月份\");\r\n");
      out.write("    \t  }\r\n");
      out.write("       }\r\n");
      out.write("   \tfunction doExport (){\r\n");
      out.write("\t\tvar d = new Date();\r\n");
      out.write("\t\tvar day = d.getHours();\r\n");
      out.write("\t\t//得到当前报表的数据量\r\n");
      out.write("\t\tvar infos = jQuery('.mini-pager-right').html()||\"\";\r\n");
      out.write("\t\tif(infos==\"\"){mini.alert(\"导出之前请查询一下。\");return false;}\r\n");
      out.write("\t\tvar pageReg = /\\d+/gi;\r\n");
      out.write("\t\tvar nums = infos.match(pageReg);\r\n");
      out.write("\t\tvar num = nums[1];\r\n");
      out.write("\t\t//如果数据量小于10000,随时可以下载\r\n");
      out.write("\t\tif(Number(num) <= 50000){\r\n");
      out.write("\t\t\t/* $(\"#id_export_message\").show(); */\r\n");
      out.write("\t\t\tmini.alert(\"正在导出请稍后......\");\t\t\t\r\n");
      out.write("\t\t\t$(\"#id_export_button\").hide();\r\n");
      out.write("\t\t\texportExcel1104('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/report/export1104Excel.action');\r\n");
      out.write("\t\t}else if(Number(num) > 50000 && Number(num) <=100000){\r\n");
      out.write("\t\t\t//在上班期间不能下载\r\n");
      out.write("\t\t\tif((day>=8 && day<12)||(day>=14&&day<18)){\r\n");
      out.write("\t\t\t\talert('抱歉，数据量过大，请在非工作期间下载！');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t/* $(\"#id_export_message\").show(); */\r\n");
      out.write("\t\t\t\tmini.alert(\"正在导出请稍后......\");\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#id_export_button\").hide();\r\n");
      out.write("\t\t\t\texportExcel1104('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/report/export1104Excel.action');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert('数据量过大，请过滤后下下载！');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("   \tfunction exportExcel1104(actionurl){\r\n");
      out.write("   \t\tvar exportObjects = new Array();\r\n");
      out.write("   \t     var data = form.getData();\r\n");
      out.write("   \t     var yearstr=mini.get(\"reportyear\").getValue();\r\n");
      out.write("\t     var newyear='';\r\n");
      out.write("\t     if(yearstr!=null||yearstr!=''){\r\n");
      out.write("\t    newyear=mini.formatDate(yearstr, \"yyyy\");\r\n");
      out.write("\t      }\r\n");
      out.write("\t     if(newyear!=null||newyear!=''){\r\n");
      out.write("\t    \tdata.reportyear=newyear;\r\n");
      out.write("\t      }\r\n");
      out.write("   \t     exportObjects.push(data);\r\n");
      out.write("   \t\tvar browser = SysBrowser.getBrowser();\r\n");
      out.write("   \t\tvar exportParams = JsonUtil.encode(exportObjects);\t\r\n");
      out.write("   \t\tvar reportname=mini.get(\"reportname\").getText();\r\n");
      out.write("   \t\tvar html = \"<form id='form_export' method='post' target='_self' action='\"+actionurl+\"'>\";\r\n");
      out.write("   \t\thtml += \"<input type='hidden' name='browser' value='\"+browser+\"'>\";\r\n");
      out.write("   \t\thtml += \"<input type='hidden' name='reportName' value='\" + reportname + \"'>\";\r\n");
      out.write("   \t\thtml += \"<input type='hidden' name='exportParams' value='\" + exportParams + \"'>\";\r\n");
      out.write("   \t\thtml += \"</form>\";\r\n");
      out.write("   \t\tvar exportFrame = jQuery('#iframe_export').contents();\r\n");
      out.write("   \t\texportFrame.find('body').html(html);\r\n");
      out.write("   \t\texportFrame.find('#form_export').submit();\r\n");
      out.write("   \t}\r\n");
      out.write("\tfunction rebackInfo(){\r\n");
      out.write("\t\tmini.alert('系统繁忙中,请不要导报表');\r\n");
      out.write("\t\t$(\"#id_export_message\").hide();\r\n");
      out.write("\t\t$(\"#id_export_button\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction rebacksuccess(){\r\n");
      out.write("\t\tmini.alert('导出成功！');\r\n");
      out.write("\t\t$(\"#id_export_message\").hide();\r\n");
      out.write("\t\t$(\"#id_export_button\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /base/var.jsp(3,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userlanguage'].language == 'zh'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\r');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /base/var.jsp(4,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("currentLocale");
    // /base/var.jsp(4,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue("zh_CN");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /base/var.jsp(6,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userlanguage'].language == 'en'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\r');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /base/var.jsp(7,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("currentLocale");
    // /base/var.jsp(7,1) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue("en_US");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /base/var.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("currentTimestamp");
    // /base/var.jsp(10,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue("20140109000");
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /base/var.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("currentSkin");
    // /base/var.jsp(11,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue("blue3");
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f4.setParent(null);
    // /base/var.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setVar("urlPrefix");
    // /base/var.jsp(12,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/table/getTableData.action?tracywindyRandom=1&decorate=none&xmlFileName=", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /base/var.jsp(12,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setScope("request");
    int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
    if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f4);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f0 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f0.setParent(null);
    // /base/var.jsp(14,24) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f0.setName("currentTimestamp");
    // /base/var.jsp(14,24) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f0.setScope("page");
    int _jspx_eval_mini_005fparam_005f0 = _jspx_th_mini_005fparam_005f0.doStartTag();
    if (_jspx_th_mini_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f1 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f1.setParent(null);
    // /base/var.jsp(15,21) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f1.setName("currentLocale");
    // /base/var.jsp(15,21) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f1.setScope("page");
    int _jspx_eval_mini_005fparam_005f1 = _jspx_th_mini_005fparam_005f1.doStartTag();
    if (_jspx_th_mini_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f2 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f2.setParent(null);
    // /base/var.jsp(16,19) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f2.setName("currentSkin");
    // /base/var.jsp(16,19) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f2.setScope("page");
    int _jspx_eval_mini_005fparam_005f2 = _jspx_th_mini_005fparam_005f2.doStartTag();
    if (_jspx_th_mini_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fscope_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f2);
    return false;
  }
}
