/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2017-05-19 05:22:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.contract.contract_005fcomm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contract_005fbase_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tlds/minidict.tld", Long.valueOf(1486341662546L));
    _jspx_dependants.put("/WEB-INF/tlds/c.tld", Long.valueOf(1486341662557L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody != null) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input name=\"contract_info.custid\" id=\"contract_info.custid\" type=\"hidden\" value=\"");
      if (_jspx_meth_mini_005fparam_005f0(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<input name=\"contract_info.contractstatus\" id=\"contract_info.contractstatus\" type=\"hidden\" value=\"");
      if (_jspx_meth_mini_005fparam_005f1(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<input name=\"contract_info.projid\" id=\"contract_info.projid\" type=\"hidden\" value=\"");
      if (_jspx_meth_mini_005fparam_005f2(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<input name=\"contract_info.id\" id=\"contract_info.id\" type=\"hidden\" value=\"");
      if (_jspx_meth_mini_005fparam_005f3(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<input name=\"contract_info.contract_id\" id=\"contract_info.contract_id\" type=\"hidden\" value=\"");
      if (_jspx_meth_mini_005fparam_005f4(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("<div id=\"contract_base_info_form\" title=\"合同基本信息\">\r\n");
      out.write("\t<div class=\"mini-panel\" title=\"合同基本信息\" showCollapseButton=\"true\" style=\"width:100%;\">\r\n");
      out.write("\t\t<table class=\"fillTable\" cellspacing=\"0\" cellpadding=\"0\" style=\"width:100%\" id=\"contract_base_info\">\r\n");
      out.write("\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\" width=\"12%\">项目编号：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\" width=\"38%\"><input name=\"contract_info.proj_id\" id=\"project_id\" class=\"mini-textbox\" label=\"项目编号\" readOnly type=\"text\" value=\"");
      if (_jspx_meth_mini_005fparam_005f5(_jspx_page_context))
        return;
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\" width=\"12%\">项目日期：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\" width=\"38%\"><input name=\"contract_info.proj_date\" id=\"proj_date\" class=\"mini-textbox\" label=\"项目日期\" readOnly type=\"text\" value=\"");
      if (_jspx_meth_mini_005fparam_005f6(_jspx_page_context))
        return;
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">系统合同编号：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\"><input id=\"contract_id\" name=\"contract_info.contractid\" class=\"mini-textbox\" label=\"系统合同编号\" allowInput=\"false\" read only value=\"");
      if (_jspx_meth_mini_005fparam_005f7(_jspx_page_context))
        return;
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">业务合同编号：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\"><input id=\"contract_number\"   name=\"contract_info.contractnumber\" required=\"true\" class=\"mini-textbox\" label=\"业务合同编号\"  allowInput=\"true\" value=\"");
      if (_jspx_meth_mini_005fparam_005f8(_jspx_page_context))
        return;
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">租赁形式：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input name=\"contract_info.leasform\" class=\"mini-combobox\" textField=\"name\" required=\"true\" label=\"租赁形式 \" valueField=\"value\" dataField=\"datas\" allowInput=\"false\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"{_params:{pid:'leas_form'}}\" onbeforeshowpopup=\"onbeforeshowpopup\" value=\"");
      if (_jspx_meth_mini_005fparam_005f9(_jspx_page_context))
        return;
      out.write("\" text=\"");
      if (_jspx_meth_mini_005fparam_005f10(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonvaluechanged=\"comboboxChanged\" />\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.leasform\" name=\"rawValue_contract_info.leasform\" value=\"");
      if (_jspx_meth_mini_005fparam_005f11(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目名称：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\" >\r\n");
      out.write("\t\t\t\t\t<input style=\"width: 60%\" name=\"contract_info.projectname\" id=\"project_name\" require=\"true\" label=\"项目名称\" class=\"mini-textbox\" readOnly type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f12(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">承租单位：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input id=\"cust_name\" name=\"contract_info.custname\" class=\"mini-textbox\" readOnly require=\"true\" label=\"承租单位\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f13(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\"><img alt=\"客户信息\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/menuIcons/search.png\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"opencustdetail('");
      if (_jspx_meth_mini_005fparam_005f14(_jspx_page_context))
        return;
      out.write('\'');
      out.write(',');
      out.write('\'');
      if (_jspx_meth_mini_005fparam_005f15(_jspx_page_context))
        return;
      out.write("')\" style=\"vertical-align: middle;\" /></a>&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">客户编号：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\"><input name=\"contract_info.custnumber\" class=\"mini-textbox\" label=\"客户编号 \" readOnly type=\"text\" value=\"");
      if (_jspx_meth_mini_005fparam_005f16(_jspx_page_context))
        return;
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t <tr class=\"tr-project-info tr-even\">   \r\n");
      out.write("\t            <td class=\"td-content-title\">联合承租人：</td>\r\n");
      out.write("\t\t        <td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t    <input class=\"mini-textbox\" id=\"custname2\"\r\n");
      out.write("\t\t\t\t\t\t type=\"text\" name=\"custname2\"\treadOnly\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t   />  \r\n");
      out.write("\t\t\t\t\t\t   <input class=\"mini-hidden\" id=\"custid2\"\r\n");
      out.write("\t\t\t\t\t\t type=\"text\" name=\"custid2\"\treadOnly\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t   />  \r\n");
      out.write("\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t <td class=\"td-content-title\">设备类型：</td>\r\n");
      out.write("\t             <td class=\"td-content-title\">\r\n");
      out.write("\t\t             <input name=\"contract_info.leastype\" id=\"leastype\" label=\"设备类型\" class=\"mini-combobox\" textField=\"name\"  required=\"true\"\r\n");
      out.write("\t\t\t                  \t   valueField=\"value\"  \r\n");
      out.write("\t\t\t\t\t\t\t\t   dataField=\"datas\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   allowInput=\"false\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   data-options=\"{_params:{pid:'leas_type'}}\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onbeforeshowpopup=\"onbeforeshowpopup\"\r\n");
      out.write("\t\t\t\t\t\t\t\t   value=\"");
      if (_jspx_meth_mini_005fparam_005f17(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   text=\"");
      if (_jspx_meth_mini_005fparam_005f18(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t   onvaluechanged=\"comboboxChanged\"/>\r\n");
      out.write("\t\t\t\t\t <font class=\"required-tag\">*</font>\r\n");
      out.write("\t\t\t\t\t <input id=\"rawValue_contract_info.leastype\" name=\"rawValue_contract_info.leastype\" value=\"");
      if (_jspx_meth_mini_005fparam_005f19(_jspx_page_context))
        return;
      out.write("\" class=\"mini-textbox\" style=\"display:none\"/>\r\n");
      out.write("\t             </td>\r\n");
      out.write("\t         </tr>\t  \r\n");
      out.write("\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目类型：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input name=\"contract_info.projtype\" class=\"mini-combobox\" textField=\"name\" readOnly required=\"true\" label=\"项目类型 \" valueField=\"value\" dataField=\"datas\" allowInput=\"false\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"{_params:{pid:'proj_type'}}\" onbeforeshowpopup=\"onbeforeshowpopup\" value=\"");
      if (_jspx_meth_mini_005fparam_005f20(_jspx_page_context))
        return;
      out.write("\" text=\"");
      if (_jspx_meth_mini_005fparam_005f21(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonvaluechanged=\"comboboxChanged(e)\"/>\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projtype\" name=\"rawValue_contract_info.projtype\" value=\"");
      if (_jspx_meth_mini_005fparam_005f22(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目规模：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input name=\"contract_info.projscale\" class=\"mini-combobox\" textField=\"name\" required=\"true\" label=\"项目规模 \" valueField=\"value\" dataField=\"datas\" allowInput=\"false\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"{_params:{pid:'proj_scale'}}\" onbeforeshowpopup=\"onbeforeshowpopup\" value=\"");
      if (_jspx_meth_mini_005fparam_005f23(_jspx_page_context))
        return;
      out.write("\" text=\"");
      if (_jspx_meth_mini_005fparam_005f24(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonvaluechanged=\"comboboxChanged\" />\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projscale\" name=\"rawValue_contract_info.projscale\" value=\"");
      if (_jspx_meth_mini_005fparam_005f25(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目来源：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input name=\"contract_info.projsource\" class=\"mini-combobox\" textField=\"name\" required=\"true\" label=\"项目来源 \" valueField=\"value\" dataField=\"datas\" allowInput=\"false\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"{_params:{pid:'proj_source'}}\" onbeforeshowpopup=\"onbeforeshowpopup\" value=\"");
      if (_jspx_meth_mini_005fparam_005f26(_jspx_page_context))
        return;
      out.write("\" text=\"");
      if (_jspx_meth_mini_005fparam_005f27(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonvaluechanged=\"comboboxChanged\" />\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projsource\" name=\"rawValue_contract_info.projsource\" value=\"");
      if (_jspx_meth_mini_005fparam_005f28(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">内部行业：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input name=\"contract_info.industrytype\" class=\"mini-combobox\" textField=\"name\" required=\"true\" label=\"内部行业 \" valueField=\"value\" dataField=\"datas\" allowInput=\"false\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"{_params:{pid:'cust_kind'}}\" onbeforeshowpopup=\"onbeforeshowpopup\" value=\"");
      if (_jspx_meth_mini_005fparam_005f29(_jspx_page_context))
        return;
      out.write("\" text=\"");
      if (_jspx_meth_mini_005fparam_005f30(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tonvaluechanged=\"comboboxChanged\" />\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.industrytype\" name=\"rawValue_contract_info.industrytype\" value=\"");
      if (_jspx_meth_mini_005fparam_005f31(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目出单部门：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input id=\"contract_info.department\" name=\"contract_info.department\" label=\"项目出单部门\" class=\"mini-buttonedit mini-queryinput\" allowInput=\"false\"\r\n");
      out.write("\t             \t\trequired=\"true\"\r\n");
      out.write("\t             \t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f32(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\ttext=\"");
      if (_jspx_meth_mini_005fparam_005f33(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.department\"\r\n");
      out.write("\t\t\t\t\t\tname=\"rawValue_contract_info.department\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f34(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">经办人：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input id=\"contract_info.projregistrar\" name=\"contract_info.projregistrar\" label=\"经办人\" class=\"mini-buttonedit mini-queryinput\" allowInput=\"false\"\r\n");
      out.write("\t             \t\trequired=\"true\"\r\n");
      out.write("\t\t\t\t\t\ttext=\"");
      if (_jspx_meth_mini_005fparam_005f35(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f36(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projregistrar\" name=\"rawValue_contract_info.projregistrar\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f37(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目经理：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input id=\"contract_info.projmanage\" name=\"contract_info.projmanage\" label=\"项目经理\" class=\"mini-buttonedit mini-queryinput\" allowInput=\"false\"\r\n");
      out.write("\t             \t\trequired=\"true\"\r\n");
      out.write("\t\t\t\t\t\ttext=\"");
      if (_jspx_meth_mini_005fparam_005f38(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f39(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projmanage\" name=\"rawValue_contract_info.projmanage\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f40(_jspx_page_context))
        return;
      out.write("\" class=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content-title\">项目协办：</td>\r\n");
      out.write("\t\t\t\t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t\t<input id=\"contract_info.projassist\" name=\"contract_info.projassist\" label=\"项目协办\" class=\"mini-buttonedit mini-queryinput\" allowInput=\"false\"\r\n");
      out.write("\t             \t\trequired=\"true\"\r\n");
      out.write("\t\t\t\t\t\ttext=\"");
      if (_jspx_meth_mini_005fparam_005f41(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f42(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t<input id=\"rawValue_contract_info.projassist\" name=\"rawValue_contract_info.projassist\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      if (_jspx_meth_mini_005fparam_005f43(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"mini-textbox\" style=\"display: none\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\tif('");
      if (_jspx_meth_mini_005fparam_005f44(_jspx_page_context))
        return;
      out.write("' == 'true' || isViewHistoryTask==true){\r\n");
      out.write("\t\tminiui_ext.disableFormFields(\"contract_base_info_form\");\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" function opencustdetail(id,custclass){\r\n");
      out.write("\t \tvar params = \"id=\"+id+\"&isView=true\";\r\n");
      out.write("\t \tvar url=\"\";\r\n");
      out.write("\t\tif(custclass==\"CUST_INFO_COMPANY\"){\r\n");
      out.write("\t\t\turl = getRootPath()+\"/leasing/cust_info/cust_company/cust_company_detail.bi?\"+params;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\turl = getRootPath()+\"/leasing/cust_info/cust_person/cust_person_detail.bi?\"+params;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar sheight = window.screen.availHeight - 30;\r\n");
      out.write("\t\tvar swidth = window.screen.availWidth - 10;\r\n");
      out.write("\t\tvar winoption = \"left=0px,top=0px,height=\" + sheight + \"px,width=\" + swidth + \"px,toolbar=yes,menubar=yes,location=yes,status=yes,scrollbars=yes,resizable=yes\";\r\n");
      out.write("\t\twindow.open(url, '_blank', winoption);\r\n");
      out.write(" }\r\n");
      out.write(" //校验业务合同编号是否重复\r\n");
      out.write(" function checkcontractnumber(){\r\n");
      out.write("\t\tvar contractnumber=$minigetvalue(\"contract_number\");\r\n");
      out.write("\t\tif(contractnumber){\r\n");
      out.write("\t\t\tcontractnumber=contractnumber.trim();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar returnresult=false;\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t \turl: urlPrefix+\"/eleasing/jsp/contract_info/check_contract_number.xml\",\r\n");
      out.write("\t\t\t    cache: false,\r\n");
      out.write("\t\t\t    async: false,\r\n");
      out.write("\t\t\t    data :{\"contractnumber\":contractnumber},\r\n");
      out.write("\t\t\t    success: function (text) {   \r\n");
      out.write("\t\t\t    \tvar result = mini.decode(text);\r\n");
      out.write("\t\t\t    \tvar res=result.datas[0].result;\r\n");
      out.write("\r\n");
      out.write("\t\t\t    \tif(res>0){\r\n");
      out.write("\t\t\t    \t\tmini.alert(\"业务合同编号【\"+contractnumber+\"】编号已存在，请修改！\");\r\n");
      out.write("\t\t\t    \t\treturnresult=true;\r\n");
      out.write("\t\t\t    \t}\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t return returnresult;\r\n");
      out.write("\t}\r\n");
      out.write(" function checkContractNumberUnique(){\r\n");
      out.write("\t   // if(mini.get(\"contract_number\").getValue() == \"\"){mini.alert(\"请填写业务合同编号！\");return false;}\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar param = {};\r\n");
      out.write("\t\tparam.xmlFileName = '/eleasing/workflow/contract/contract_comm/get_contract_by_contractnumber.xml';\r\n");
      out.write("\t\tparam.contractnumer = mini.get(\"contract_number\").getValue();\r\n");
      out.write("\t\tajaxRequest({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/table/getTableData.action',\r\n");
      out.write("\t\t\tmethod : 'POST',\r\n");
      out.write("\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\tvar scustinfo = res.responseText;\r\n");
      out.write("\t\t\t\tscustinfo = scustinfo.replace(/(^\\s+)|(\\s+$)/g, \"\");\r\n");
      out.write("\t\t\t\tvar obj =mini.decode(scustinfo);\r\n");
      out.write("\t\t\t\tif(\"\" != obj.datas){\r\n");
      out.write("\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : false,\r\n");
      out.write("\t\t\tfailure : function(res) {\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tparams : param\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tif(flag==true){mini.alert(\"该业务合同编号已存在！\");}\r\n");
      out.write("\t\treturn flag;\r\n");
      out.write("\t}\r\n");
      out.write(" jQuery(function(){\r\n");
      out.write("\t\tvar strs = [{key:\"contract_info.projassist\",value:\"项目协办\"},{key:\"contract_info.projmanage\",value:\"项目经理\"},{key:\"contract_info.projregistrar\",value:\"经办人\"}];\r\n");
      out.write("\t\tfor(var i = 0 ;i<strs.length;i++){\r\n");
      out.write("\t\t\ttenwa.createQueryInput({ \r\n");
      out.write("\t\t\t\tid:strs[i].key,\r\n");
      out.write("\t\t\t\tlabel:strs[i].value,\r\n");
      out.write("\t\t\t\twindowWidth: 600,\r\n");
      out.write("\t\t\t\ttextField:\"name\",\r\n");
      out.write("\t\t      \tvalueField:\"id\",\r\n");
      out.write("\t\t\t\tonSelect: function($me, inputObj, rowData){\r\n");
      out.write("\t\t\t\t\tmini.get(\"rawValue_\"+inputObj.id).setValue(rowData.name);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tparams: {\r\n");
      out.write("\t\t\t\t\txmlFileName: '/eleasing/workflow/proj/proj_common/creator_combox.xml'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttenwa.createQueryInput({\r\n");
      out.write("\t\t\tid:'contract_info.department',\r\n");
      out.write("\t\t\tlabel:'项目出单部门',\r\n");
      out.write("\t\t\ttextField:\"name\",\r\n");
      out.write("\t      \tvalueField:\"id\",\r\n");
      out.write("\t\t\twindowWidth: 600,\r\n");
      out.write("\t\t\tonSelect: function($me, inputObj, rowData){\r\n");
      out.write("\t\t\t\tmini.get(\"rawValue_contract_info.department\").setValue(rowData.name);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tparams: {\r\n");
      out.write("\t\t\t\txmlFileName: '/eleasing/workflow/proj/proj_common/department_combox.xml'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mini_005fparam_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f0 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f0.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(4,82) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f0.setName("contract_info.custid");
    int _jspx_eval_mini_005fparam_005f0 = _jspx_th_mini_005fparam_005f0.doStartTag();
    if (_jspx_th_mini_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f1 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f1.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(5,98) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f1.setName("contract_info.contractstatus");
    int _jspx_eval_mini_005fparam_005f1 = _jspx_th_mini_005fparam_005f1.doStartTag();
    if (_jspx_th_mini_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f2 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f2.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(6,82) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f2.setName("contract_info.projid");
    int _jspx_eval_mini_005fparam_005f2 = _jspx_th_mini_005fparam_005f2.doStartTag();
    if (_jspx_th_mini_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f2);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f3 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f3.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f3.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(7,74) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f3.setName("contract_info.id");
    int _jspx_eval_mini_005fparam_005f3 = _jspx_th_mini_005fparam_005f3.doStartTag();
    if (_jspx_th_mini_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f3);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f4 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f4.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f4.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(8,92) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f4.setName("contract_info.contract_id");
    int _jspx_eval_mini_005fparam_005f4 = _jspx_th_mini_005fparam_005f4.doStartTag();
    if (_jspx_th_mini_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f4);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f5 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f5.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f5.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(14,153) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f5.setName("contract_info.proj_id");
    int _jspx_eval_mini_005fparam_005f5 = _jspx_th_mini_005fparam_005f5.doStartTag();
    if (_jspx_th_mini_005fparam_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f5);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f6 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f6.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f6.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(16,154) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f6.setName("contract_info.projdate");
    int _jspx_eval_mini_005fparam_005f6 = _jspx_th_mini_005fparam_005f6.doStartTag();
    if (_jspx_th_mini_005fparam_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f6);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f7 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f7.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f7.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(20,155) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f7.setName("contract_info.contractid");
    int _jspx_eval_mini_005fparam_005f7 = _jspx_th_mini_005fparam_005f7.doStartTag();
    if (_jspx_th_mini_005fparam_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f7);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f8 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f8.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f8.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(22,171) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f8.setName("contract_info.contractnumber");
    int _jspx_eval_mini_005fparam_005f8 = _jspx_th_mini_005fparam_005f8.doStartTag();
    if (_jspx_th_mini_005fparam_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f8);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f9 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f9.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f9.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(28,94) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f9.setName("contract_info.leasform");
    int _jspx_eval_mini_005fparam_005f9 = _jspx_th_mini_005fparam_005f9.doStartTag();
    if (_jspx_th_mini_005fparam_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f9);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f10 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f10.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f10.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(28,146) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f10.setName("rawValue_contract_info.leasform");
    int _jspx_eval_mini_005fparam_005f10 = _jspx_th_mini_005fparam_005f10.doStartTag();
    if (_jspx_th_mini_005fparam_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f10);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f11 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f11.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f11.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(30,95) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f11.setName("rawValue_contract_info.leasform");
    int _jspx_eval_mini_005fparam_005f11 = _jspx_th_mini_005fparam_005f11.doStartTag();
    if (_jspx_th_mini_005fparam_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f11);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f12 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f12.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f12.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(36,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f12.setName("contract_info.projectname");
    int _jspx_eval_mini_005fparam_005f12 = _jspx_th_mini_005fparam_005f12.doStartTag();
    if (_jspx_th_mini_005fparam_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f12);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f13 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f13.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f13.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(43,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f13.setName("contract_info.custname");
    int _jspx_eval_mini_005fparam_005f13 = _jspx_th_mini_005fparam_005f13.doStartTag();
    if (_jspx_th_mini_005fparam_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f13);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f14 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f14.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f14.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(46,31) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f14.setName("contract_info.custid");
    int _jspx_eval_mini_005fparam_005f14 = _jspx_th_mini_005fparam_005f14.doStartTag();
    if (_jspx_th_mini_005fparam_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f14);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f15 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f15.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f15.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(46,76) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f15.setName("contract_info.custclass");
    int _jspx_eval_mini_005fparam_005f15 = _jspx_th_mini_005fparam_005f15.doStartTag();
    if (_jspx_th_mini_005fparam_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f15);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f16 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f16.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f16.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(49,129) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f16.setName("contract_info.custnumber");
    int _jspx_eval_mini_005fparam_005f16 = _jspx_th_mini_005fparam_005f16.doStartTag();
    if (_jspx_th_mini_005fparam_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f16);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f17 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f17.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f17.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(69,18) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f17.setName("contract_info.leastype");
    int _jspx_eval_mini_005fparam_005f17 = _jspx_th_mini_005fparam_005f17.doStartTag();
    if (_jspx_th_mini_005fparam_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f17);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f18 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f18.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f18.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(70,17) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f18.setName("rawValue_contract_info.leastype");
    int _jspx_eval_mini_005fparam_005f18 = _jspx_th_mini_005fparam_005f18.doStartTag();
    if (_jspx_th_mini_005fparam_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f18);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f18);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f19 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f19.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f19.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(73,96) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f19.setName("rawValue_contract_info.leastype");
    int _jspx_eval_mini_005fparam_005f19 = _jspx_th_mini_005fparam_005f19.doStartTag();
    if (_jspx_th_mini_005fparam_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f19);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f19);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f20 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f20.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f20.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(80,94) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f20.setName("contract_info.projtype");
    int _jspx_eval_mini_005fparam_005f20 = _jspx_th_mini_005fparam_005f20.doStartTag();
    if (_jspx_th_mini_005fparam_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f20);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f20);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f21 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f21.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f21.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(80,146) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f21.setName("rawValue_contract_info.projtype");
    int _jspx_eval_mini_005fparam_005f21 = _jspx_th_mini_005fparam_005f21.doStartTag();
    if (_jspx_th_mini_005fparam_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f21);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f21);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f22(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f22 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f22.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f22.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(82,95) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f22.setName("rawValue_contract_info.projtype");
    int _jspx_eval_mini_005fparam_005f22 = _jspx_th_mini_005fparam_005f22.doStartTag();
    if (_jspx_th_mini_005fparam_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f22);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f22);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f23 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f23.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f23.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(88,95) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f23.setName("contract_info.projscale");
    int _jspx_eval_mini_005fparam_005f23 = _jspx_th_mini_005fparam_005f23.doStartTag();
    if (_jspx_th_mini_005fparam_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f23);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f23);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f24(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f24 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f24.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f24.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(88,148) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f24.setName("rawValue_contract_info.projscale");
    int _jspx_eval_mini_005fparam_005f24 = _jspx_th_mini_005fparam_005f24.doStartTag();
    if (_jspx_th_mini_005fparam_005f24.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f24);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f24);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f25(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f25 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f25.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f25.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(90,97) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f25.setName("rawValue_contract_info.projscale");
    int _jspx_eval_mini_005fparam_005f25 = _jspx_th_mini_005fparam_005f25.doStartTag();
    if (_jspx_th_mini_005fparam_005f25.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f25);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f25);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f26(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f26 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f26.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f26.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(97,96) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f26.setName("contract_info.projsource");
    int _jspx_eval_mini_005fparam_005f26 = _jspx_th_mini_005fparam_005f26.doStartTag();
    if (_jspx_th_mini_005fparam_005f26.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f26);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f26);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f27(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f27 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f27.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f27.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(97,150) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f27.setName("rawValue_contract_info.projsource");
    int _jspx_eval_mini_005fparam_005f27 = _jspx_th_mini_005fparam_005f27.doStartTag();
    if (_jspx_th_mini_005fparam_005f27.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f27);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f27);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f28(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f28 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f28.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f28.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(99,99) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f28.setName("rawValue_contract_info.projsource");
    int _jspx_eval_mini_005fparam_005f28 = _jspx_th_mini_005fparam_005f28.doStartTag();
    if (_jspx_th_mini_005fparam_005f28.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f28);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f28);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f29(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f29 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f29.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f29.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(105,94) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f29.setName("contract_info.industrytype");
    int _jspx_eval_mini_005fparam_005f29 = _jspx_th_mini_005fparam_005f29.doStartTag();
    if (_jspx_th_mini_005fparam_005f29.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f29);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f29);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f30(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f30 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f30.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f30.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(105,150) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f30.setName("rawValue_contract_info.industrytype");
    int _jspx_eval_mini_005fparam_005f30 = _jspx_th_mini_005fparam_005f30.doStartTag();
    if (_jspx_th_mini_005fparam_005f30.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f30);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f30);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f31(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f31 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f31.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f31.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(107,103) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f31.setName("rawValue_contract_info.industrytype");
    int _jspx_eval_mini_005fparam_005f31 = _jspx_th_mini_005fparam_005f31.doStartTag();
    if (_jspx_th_mini_005fparam_005f31.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f31);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f31);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f32(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f32 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f32.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f32.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(116,23) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f32.setName("contract_info.department");
    int _jspx_eval_mini_005fparam_005f32 = _jspx_th_mini_005fparam_005f32.doStartTag();
    if (_jspx_th_mini_005fparam_005f32.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f32);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f32);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f33(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f33 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f33.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f33.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(117,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f33.setName("rawValue_contract_info.department");
    int _jspx_eval_mini_005fparam_005f33 = _jspx_th_mini_005fparam_005f33.doStartTag();
    if (_jspx_th_mini_005fparam_005f33.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f33);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f33);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f34(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f34 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f34.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f34.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(121,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f34.setName("rawValue_contract_info.department");
    int _jspx_eval_mini_005fparam_005f34 = _jspx_th_mini_005fparam_005f34.doStartTag();
    if (_jspx_th_mini_005fparam_005f34.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f34);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f34);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f35(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f35 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f35.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f35.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(128,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f35.setName("rawValue_contract_info.projregistrar");
    int _jspx_eval_mini_005fparam_005f35 = _jspx_th_mini_005fparam_005f35.doStartTag();
    if (_jspx_th_mini_005fparam_005f35.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f35);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f35);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f36(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f36 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f36.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f36.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(129,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f36.setName("contract_info.projregistrar");
    int _jspx_eval_mini_005fparam_005f36 = _jspx_th_mini_005fparam_005f36.doStartTag();
    if (_jspx_th_mini_005fparam_005f36.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f36);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f36);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f37(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f37 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f37.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f37.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(132,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f37.setName("rawValue_contract_info.projregistrar");
    int _jspx_eval_mini_005fparam_005f37 = _jspx_th_mini_005fparam_005f37.doStartTag();
    if (_jspx_th_mini_005fparam_005f37.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f37);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f37);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f38(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f38 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f38.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f38.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(141,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f38.setName("rawValue_contract_info.projmanage");
    int _jspx_eval_mini_005fparam_005f38 = _jspx_th_mini_005fparam_005f38.doStartTag();
    if (_jspx_th_mini_005fparam_005f38.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f38);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f38);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f39(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f39 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f39.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f39.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(142,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f39.setName("contract_info.projmanage");
    int _jspx_eval_mini_005fparam_005f39 = _jspx_th_mini_005fparam_005f39.doStartTag();
    if (_jspx_th_mini_005fparam_005f39.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f39);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f39);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f40(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f40 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f40.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f40.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(145,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f40.setName("rawValue_contract_info.projmanage");
    int _jspx_eval_mini_005fparam_005f40 = _jspx_th_mini_005fparam_005f40.doStartTag();
    if (_jspx_th_mini_005fparam_005f40.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f40);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f40);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f41(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f41 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f41.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f41.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(151,12) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f41.setName("rawValue_contract_info.projassist");
    int _jspx_eval_mini_005fparam_005f41 = _jspx_th_mini_005fparam_005f41.doStartTag();
    if (_jspx_th_mini_005fparam_005f41.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f41);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f41);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f42(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f42 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f42.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f42.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(152,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f42.setName("contract_info.projassist");
    int _jspx_eval_mini_005fparam_005f42 = _jspx_th_mini_005fparam_005f42.doStartTag();
    if (_jspx_th_mini_005fparam_005f42.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f42);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f42);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f43(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f43 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f43.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f43.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(155,13) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f43.setName("rawValue_contract_info.projassist");
    int _jspx_eval_mini_005fparam_005f43 = _jspx_th_mini_005fparam_005f43.doStartTag();
    if (_jspx_th_mini_005fparam_005f43.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f43);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f43);
    return false;
  }

  private boolean _jspx_meth_mini_005fparam_005f44(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mini:param
    com.tenwa.leasing.tag.GetParameter _jspx_th_mini_005fparam_005f44 = (com.tenwa.leasing.tag.GetParameter) _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.get(com.tenwa.leasing.tag.GetParameter.class);
    _jspx_th_mini_005fparam_005f44.setPageContext(_jspx_page_context);
    _jspx_th_mini_005fparam_005f44.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/contract/contract_comm/contract_base_info.jsp(164,5) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_mini_005fparam_005f44.setName("isView");
    int _jspx_eval_mini_005fparam_005f44 = _jspx_th_mini_005fparam_005f44.doStartTag();
    if (_jspx_th_mini_005fparam_005f44.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f44);
      return true;
    }
    _005fjspx_005ftagPool_005fmini_005fparam_0026_005fname_005fnobody.reuse(_jspx_th_mini_005fparam_005f44);
    return false;
  }
}
